### ISSUE TITLE
Track Survey Design Products for Runs including Run 1.1

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/DC2-production#110]
The survey design products that will be used during simulations of different runs are:
- [x] `minion_1016_desc_dithered_vn.db` an OpSim like database with additional columns with the positional and rotational dithers used for DC2.
- [x] Set of OpSim visits that are included in the simulation

These also depend on a set of underlying data products 
- [x] `minion_1016_desc_vn.db` An undithered version of OpSim Database
- [x] Set of visits that overlap the main and uDDF survey region in WFD and DDF

which in turn depend on a set of inputs and decisions that were taken. 

We should track the versions of the set of products used for simulations, the underlying set inputs and decisions for each set of products which we then use in simulations. As has been discussed in #83 and other places: We will have versions of these products on nersc directories, but will keep documents that note the progress with version upgrades on this repository. The versions that we will use in simulation runs (like 1.1 or later) should be on the google doc notes for DC2. For this purpose I propose  having a directory in documents with a README file describing each of the products (including locations) and new columns we have added, and the input in notes corresponding to the product, and a csv file which shows the set of associated products. As an example I will make a PR putting such a directory in the Documents directory of this repository (but can move it elsewhere).

**Comment by katrinheitmann** [comment]
@rbiswas4 This one can be closed now also, right? Thanks!

**Comment by rbiswas4** [comment]
Might be good to keep this open as  DC2 project tracker for completing the notes, which are not done yet. Sorry! 

Keeping this open helps letting you keep tabs on us. That is useful I think.

**Comment by katrinheitmann** [comment]
@rbiswas4 Now the notes are complete, right? Do you want to close this?

**Comment by cwwalter** [comment]
@rbiswas4 Can this be closed now? As @katrinheitmann pointed out I think the notes are done now.
