### ISSUE TITLE
Avoid using knots in sprinkled galaxies

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2-production#128]
@danielsf @EiffL @jbkalmbach should discuss this at SLAC Collaboration Meeting

**Comment by EiffL** [comment]
I'm looking at the sprinkler code in the sims_GCRCatSimInterface to make sure everything works with galaxy knots. One basic question, are we planning to use the version on master for DC2, or should I work on an earlier tagged version ?

**Comment by jbkalmbach** [comment]
I think you can go with master in that repo since we recently merged the static lens functionality to run in DC2 to master.

**Comment by EiffL** [comment]
Hi @jbkalmbach, actually, we implemented a mechanism last week to disable the knots on faint galaxies already, I'm thinking the same thing could be applied here. It would be easy if you could somehow add a flag to the catalog saying whether a galaxy is sprinkled or not, then it could be used here: https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/a6e60cf8a33fbecd177a81296fc1a3e1ff1516b7/python/desc/sims/GCRCatSimInterface/DatabaseEmulator.py#L390
This is where the decision is made whether to apply the knots or not, it's only based on i band magnitude for now, but that's where it's likely to be the simplest.

**Comment by jbkalmbach** [comment]
@danielsf Do you think we could just use the `is_sprinkled` tag that you've already written here or do we need another way?

**Comment by danielsf** [comment]
I don't think so.  `is_sprinkled` is only added to the catalog query after the sprinkler has been run.  The code Francois pointed to gets run the moment that cosmoDC2 is loaded into memory.

Given that you are precaching a list of galaxies that will get sprinkled, anyway, it might be easier to just edit the block of code Francois pointed to so that it looks up the `galaxy_id`s of galaxies destined to be sprinkled and ignores those, as well.

**Comment by danielsf** [comment]
@jbkalmbach We have fixed this, correct?

**Comment by jbkalmbach** [comment]
I'm pretty sure we have, but let me look up what we did and document our solution here.

**Comment by jbkalmbach** [comment]
@danielsf I'm not sure exactly where the code is but we discussed just turning off the knots for sprinkled systems. Possibly with the cached IDs of sprinkled systems.

**Comment by danielsf** [comment]
You're right.  The relevant line of code is here

https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/python/desc/sims/GCRCatSimInterface/CatalogClasses.py#L382

It turns off the knots if `is_sprinkled` is `True`
