### ISSUE TITLE
Making larger sprinkled AGN catalog

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2-production#130]
@drphilmarshall In Run 1.1 we are still only using the Rung 4 lenses from the TDC. For the next run should we expand the Twinkles catalog to include all lenses from the TDC? 

Also note that since the Run 1.1 used proto-DC2 galaxies which only go out to z=1.0 this leads to a lot of repeating of the lensed AGN systems to get to the goal of ~1000 in the uDDF field.

**Comment by drphilmarshall** [comment]
Good point about the source AGN redshift limit - that will have implications for the Run 1.1 observability of lensed AGN (they will tend to have small image separations). I'm not too worried about replicating systems - it allows a test where we sample the space of possible variability parameters. In Run 2 we'll need input from the SL group on the sample design: if there's a _detection_ element to their investigations (as well as a light curve _measurement_ element), then they may well want to push down in to the OM10 population to fainter images, etc.  cc: @tcollett @dannygoldstein to get this on their discussion agenda.

**Comment by jbkalmbach** [comment]
We are using the full OM10 catalog to match in the sprinkler now so I think we can close this issue.
