### ISSUE TITLE
Utilities for making coverage and depth maps of simulated data

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/DC2-production#137]
I was just chatting with Phil, and we were wondering how to track the progress of our Run1.1p simulations as the data are being generated.  We'd like to project how well the proposed simulations would have sufficient coverage, etc., to be useful at the end of our nominal 3 days of compute time, or if additional visits would need to be run (perhaps just for some of our 12 visit lists), or if current data are already enough thereby allowing us to stop the sims early.

So the proposal would be to have some code to make coverage and depth maps given the current set of data.  @fjaviersanchez Didn't you make these sorts of maps for DC1 based on the calexps?  Would there be a way to do this more approximately without needing to run `processEimage.py`?  @humnaawan I think you also had tools to predict coverage and depth in designing the dithering patterns.  Could they be adapted here?

**Comment by fjaviersanchez** [comment]
@jchiang87 I use the catalogs to build the depth maps and I have code to estimate the predicted depth given the background levels but, the predicted value and the measured value were a little bit off:

![image](https://user-images.githubusercontent.com/13971732/36556219-4d60b1a4-17b9-11e8-9518-f28d8495d3a2.png)

**Comment by fjaviersanchez** [comment]
I have this code (that was in the Monitor repo) to get an estimate of the depth given the background
``
def get_5s_depth_butler(calexp,catalog=None):
    """Routine from https://github.com/LSSTDESC/Monitor/blob/master/python/desc/monitor/monitor.py
    and https://github.com/LSSTDESC/pserv/blob/master/python/desc/pserv/utils.py"""
    psf_area = calexp.getInfo().getPsf().computeShape().getArea()
    skyNoise = lsst.afw.math.makeStatistics(calexp.getMaskedImage(),lsst.afw.math.STDEVCLIP).getValue()
    sky_noise_5_sigma = (5*1e9*skyNoise)
    calib = calexp.getCalib()
    calib.setThrowOnNegativeFlux(False)
    visit_depths = 22.5 - 2.5*np.log10((sky_noise_5_sigma * psf_area) / calib.getFluxMag0()[0])
    if catalog is not None:
        psfmag, psfmagerr = calib.getMagnitude(catalog.getPsfFlux(), catalog.getPsfFluxErr())
        good = np.logical_and(~np.isnan(psfmag),catalog.getPsfFlux()/catalog.getPsfFluxErr()>=5.)
        good_star = np.logical_and(good,catalog.get("base_ClassificationExtendedness_value")==0)
        visit_depths2 = np.max(psfmag[good_star])
        return visit_depths, visit_depths2
    else:
        return visit_depths, 0``

**Comment by drphilmarshall** [comment]
I think for a first cut at this we could measure "depth" at each point on
the sky just by number of visits. Suppose we ran a modified version of
Humna's animated field visualization code, but 1) plotted the sensors that
have been simulated as shaded regions with `alpha=0.01`, and 2) did not
clear the plot inbetween frames. The result should be an animation of the
field being "colored in" as the visits are simulated. I guess we'd want to
do one of these for each filter (using a different color for the shading
each time). Not sure whether it should be one animation frame per sensor,
or one per full frame visit - maybe the latter is more realistic (because
unless a sensor fails, we'll always get complete full frame visits off the
telescope - and so I assume we are always willing to wait for all sensor
visits in a full frame visit to complete).

**Comment by astrostubbs** [comment]
Just a cautionary note that we're rapidly moving away from the concept of "fields"...

Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

Think this email is terse? Here's why:
http://www.emailcharter.org

**Comment by cwwalter** [comment]
> Just a cautionary note that we're rapidly moving away from the concept of "fields"...

Can you say a bit more about what this means?

**Comment by astrostubbs** [comment]
The scheduling algorithms that are presently under development accomplish "dithering" by effectively randomizing the tiling centers at the start of each night. So the concept of fixed fields really doesn't make sense. We visualize sky coverage by asking how often a given healpix pixel gets imaged. 
C

Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

Think this email is terse? Here's why:
http://www.emailcharter.org

**Comment by cwwalter** [comment]
I see.  OK, I got it. Thanks!

**Comment by RobertLuptonTheGood** [comment]
While the scheduler doesn't think in terms of fields, I think that the users will.  For example, I expect that we'll be building and processing coadds on "tracts" of c. 10 deg^2, and those *will* have well-defined centres.

						R

**Comment by jchiang87** [comment]
This is addressed by code in https://github.com/LSSTDESC/desc_sim_utils and https://github.com/LSSTDESC/supreme
