### ISSUE TITLE
Verification codes for sprinkler

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2-production#139]
At the Hack Day at SLAC I started work on some codes to check that the properties of the sprinkled lensed systems in the instance catalogs matched the properties from the original input catalogs from which we draw them. At the Hack Day I finished a position matcher that makes sure the locations of the ra, dec of the lensed images compared to the lens galaxy are correct (see image below).

Other things to check with the code are the variability of the images including the time delays, the magnitudes and the colors. Suggestions for other tests are welcome.

For now this code is being developed in the Twinkles repo but if there's a better place for it, it can go there.

<img width="541" alt="hack_screenshot" src="https://user-images.githubusercontent.com/4755090/36611483-707cdc4c-1888-11e8-9498-f9ea5253c448.png">

**Comment by drphilmarshall** [comment]
Nice! :-) Maybe some lens galaxy tests, like size and magnitudes/colors,
and (less importantly?) ellipticity and orientation?

**Comment by katrinheitmann** [comment]
@jbkalmbach Any updates on this issue? Thanks a lot!

**Comment by jbkalmbach** [comment]
Ok, the code to check the Instance Catalogs has been merged in LSSTDESC/Twinkles/pull/473. So, I think this issue can go ahead and be closed.
