### ISSUE TITLE
ImSim GridPP operations log

### ISSUE THREAD

**Issue by jamesp-epcc** [LSSTDESC/DC2-production#173]
This issue is intended to log the progress of the DC2 ImSim runs on GridPP resources in the UK. The intention is to do Run1.2p on ImSim using GridPP. Currently, the required software has been installed on GridPP, several problems have been overcome and test jobs have been run. However the results are currently not matching results from running at NERSC so this needs to be fixed before production runs can start.

## Installing the software

GridPP uses [CernVM File System](https://cernvm.cern.ch/portal/filesystem) for software distribution. This allows software to be installed once and easily made available on all the grid's compute resources in the `/cvmfs` directory.

The software required for the ImSim runs has been installed in `/cvmfs/gridpp.egi.eu/lsst/`. It was built on a Scientific Linux 6.9 virtual machine in order to be as close as possible to the environment on the grid nodes. `lsst_distrib` version `w_2018_19` and `lsst_sims` version `sims_2_8_0` were installed via `eups`, and the `multiprocessing_treering_atm_merge` branch of ImSim was deployed on top.

## Running ImSim on the grid

ImSim jobs are submitted to the job using the [Ganga interface](https://www.gridpp.ac.uk/userguide/). Input data (instance catalogs) and output data (FITS files) are read from and written to grid storage elements.

ImSim's resource requirements posed a few problems. In order to allocate enough memory (~11GB is required) to run successfully it was necessary to request multiple CPU cores, since most GridPP nodes only provide 2-4GB per core. However the LSST virtual organisation did not initially have the necessary permission to do this. This permission has now been granted.

The next problem related to the run time of the jobs. A full run of all the sensors for a particular visit takes more than 48 hours, which is normally the maximum length of time that jobs are allowed to run for on the grid. To get around this, the jobs have been split up so that each job processes a maximum of 4 sensors. A process per sensor is used to improve the performance and these jobs now complete in around 2 hours each.

## Automation

A number of scripts have been written to partially automate the use of the grid, and these can be found at https://github.com/LSSTDESC/imsim-scripts-dc2/tree/master/gridpp . There are Python scripts that can be run within Ganga in order to submit jobs (either single jobs for testing purposes, or batches of jobs for production runs), rerun failed jobs, and monitor the progress of jobs. There are also Bash scripts which assist with copying input data (instance catalogs) from NERSC onto grid storage elements and transferring output data from the grid to NERSC. These scripts depend on the Dirac file catalog tools.

Further automation may be possible once production runs are underway.

**Comment by jamesp-epcc** [comment]
It appears I don't have permission to assign this to myself; could someone do that please?

**Comment by jamesp-epcc** [comment]
# Early job runs

A single visit from each band of the WFD survey has already been run on the grid. The visits selected were:

Band | Visit
---- | -----
u | 000018
g | 000027
z | 000025
y | 000077
r | 000094
i | 000057

These have all now completed and the output data has been copied to `/global/cscratch1/sd/jamesp/DC2output` on Cori.

The instance catalogs for the i band of the WFD survey have all been uploaded to grid storage elements. The first 10 visits for this band have been run on the grid. The average run time for these jobs was 2h10m56s and the throughput was around 400 jobs in 24 hours. Better monitoring is necessary to get a more accurate idea of how long the full production runs might take. The output from these runs is also on Cori.

**Comment by jamesp-epcc** [comment]
![runtimes](https://user-images.githubusercontent.com/14821192/42165613-809da060-7e00-11e8-91b0-470814aea7cc.png)
![waittimes](https://user-images.githubusercontent.com/14821192/42165627-8c368194-7e00-11e8-9203-2bce6e3a479f.png)
These graphs show the distribution of job run times and wait times for around 400 of the i-band jobs.

**Comment by cwwalter** [comment]
Thanks!  Can you also make one which is a pure wait time?

**Comment by jamesp-epcc** [comment]
Sorry, I'm not sure what you mean. The second graph shows only the wait time (the time between submission and when the job actually starts to run). Could you explain what you mean by pure wait time?

**Comment by cwwalter** [comment]
Sorry, I misread the text "These graphs show the distribution of job run times and wait times for around 400 of the i-band jobs." as the caption for the 2nd graph.  

This is in fact what I wanted. 

Do we have the same thing for the other bands?

**Comment by cwwalter** [comment]
I expect the cpu time to be the same in the other bands BTW. The way the sky background is generated should be time independent of the brightness.

**Comment by jamesp-epcc** [comment]
I don't have the information needed to generate this for the other bands - I have been removing old jobs from the system to stop my Ganga environment from getting too out of hand. However I am going to rerun all the jobs I previously ran in the other bands once I've updated the software to 2.9.0, so I can generate the graphs then.

**Comment by jamesp-epcc** [comment]
![runtimes](https://user-images.githubusercontent.com/14821192/42442497-bcba9ef6-8362-11e8-88f1-5a9a0955af4a.png)
![waittimes](https://user-images.githubusercontent.com/14821192/42442498-bcd51f42-8362-11e8-9593-48e1258c9159.png)
The test visits for the 6 bands have now been rerun using the 2.9.0 sims software. Job run and wait times are shown in the graphs above. 15 out of 312 jobs failed and are currently being rerun. Output data is being uploaded to Cori for checking.

**Comment by drphilmarshall** [comment]
Thanks James! It's great to see the ImSim images streaming in, with the UK
grid humming away :-)

From your plots I am taking away that a single sensor visit image takes
about 30 mins to make (on average), and you typically have to wait about a
day for it to start (although it can be much sooner). So are you still
running about 400 jobs in 24 hours, on average? That's an overall
simulation speed of something like 1 full-focal plane visit image every 3
hours, unless I have done my sums wrong. The gold standard in image
generation is the LSST itself, which will run about 320 times faster (1
full-focal plane visit image every 34 seconds). What would it take to get
320 times more grid nodes fired up, to run 128000 jobs per day? :-)

**Comment by salmanhabib** [comment]
Why is the sensor visit so slow? Maybe that's what really needs fixing.

**Comment by cwwalter** [comment]
Hi Salman,

Actually I think it is a bit longer than what Phil says .  The average wall clock time is about 120 minutes (two hours).  But, I'm confused why you think it is too slow... you can compare it with (for example) the PhoSim times in Tom's log which depending on the band are typically in the 100-400 hours range (although it isn't a one-to-one comparison because of KNL etc).

Once difference here is that we are using multiprocessing instead of multi-threading. So we have 4 jobs on each node and each is running the whole sensor visit to completion.  Is that the difference you mean? Or is there something else you think we can speed up?

I actually suspect we can make things go faster.  For one thing the stack on Linux is still not using MKL libraries and I hope my using some of the tools Adrian was telling us about we could really pinpoint performance issues.  But, any insight you have would be great.

**Comment by cwwalter** [comment]
Well.. Keep in mind we are now in fact transporting photons through the atmosphere etc and propagating photons into the silicon.  So, we also have an emergent PSF.  We can turn those features off in imSim and do it all parametrically and, as I recall, it takes more like 20 minutes (this is for ~100,000 sources).  Jim might be able to confirm. Because of the way we handle sky photons it is fixed and small time.

We did do some basic profiling when we were developing the silicon code which interpolated Craig's model. But, I don't think we have answers to the kinds of questions you are asking yet.

**Comment by cwwalter** [comment]
Jim and @rmjarvis could say more especially about core GalSim functions.

**Comment by salmanhabib** [comment]
BTW, are you transporting through the optics or using a matrix approximation?

**Comment by jamesp-epcc** [comment]
Hi Phil,
I haven't yet started on regularly running large numbers of jobs as we were waiting for the background mismatch between GridPP and NERSC runs to be fixed. It is fixed now so I am about to start on the large scale runs. I should have a better idea of overall throughput after these have been ongoing for a while.

**Comment by cwwalter** [comment]
Hi Salman,

We don't have raytracing through the optical elements yet.

**Comment by salmanhabib** [comment]
@cwwalter Is there a (howsoever a crude) write-up somewhere on the latest incarnation of ImSim?

**Comment by rmjarvis** [comment]
I'm not sure what I'm being asked to comment on here.  But if this is considered too slow, then it would be helpful to see a cProfile output to know where the hot spots are.  Otherwise I'll probably end up describing a whole bunch of things that aren't relevant to the performance.

**Comment by drphilmarshall** [comment]
Thanks James, thanks all. "Overall throughput" is indeed what I was after -
maybe I misconstrued James' earlier log, I thought that each "job" took 2
hours and resulted in 4 sensor visit images, hence 30 minutes per sensor
visit image on average. Agreed that some profiler output would be most
interesting - and a valuable addition to the relevant ImSim write-up.
Interested to see how many grid nodes you can wrangle, James! :-)

**Comment by jamesp-epcc** [comment]
The first 7 visits of the i band are complete (apart from a few reruns for failed jobs) and several more are in progress. Run time and wait time graphs for the first 7 visits are shown below.
![runtimes](https://user-images.githubusercontent.com/14821192/42575761-1d8cf0fa-8519-11e8-8058-b5df8b2fe393.png)
![waittimes](https://user-images.githubusercontent.com/14821192/42575763-1da67750-8519-11e8-8aab-6b531903abb8.png)

**Comment by jamesp-epcc** [comment]
Run time and wait time graphs for a much larger number of jobs (i band visits 30-79 plus a few later ones). The run times still cluster round an average of just over two hours, though some take significantly longer. I'm not sure why that is; it might be because of delays in the batch system registering them as completed and uploading their output rather than anything slowing down the actual compute.

The wait times vary a lot more than before, probably because I've been saturating the grid with jobs lately so some of them have to wait a lot longer before resources become available for them.
![runtimes](https://user-images.githubusercontent.com/14821192/42996207-c5367d56-8c0a-11e8-9f3f-a2320583133e.png)
![waittimes](https://user-images.githubusercontent.com/14821192/42996209-c5532d66-8c0a-11e8-8c4a-670d5ce8e7c0.png)

**Comment by jamesp-epcc** [comment]
Run time and wait time graphs for 2800 jobs from the last day (approximately). Waiting times have generally decreased due to changes to the grid configuration making more multicore job slots available, and all the jobs ran within 15 hours of submission.
Run times remain similar with a peak around the 2 hour mark. The large spike on the far left of the graph is the jobs for which none of the objects in the instance catalog produced any output on the sensors being simulated. The reason this didn't appear in previous graphs is that initially these jobs were classified as "failed" by the grid software due to not producing the expected output files, and so didn't count towards the timing statistics. The submission scripts have now been modified so that the jobs succeed, since this is expected behaviour for the data sets in question.
![runtimes](https://user-images.githubusercontent.com/14821192/43950988-d1ea9e62-9c89-11e8-9cde-1c4306e20ffe.png)
![waittimes](https://user-images.githubusercontent.com/14821192/43950989-d20518be-9c89-11e8-9af2-57c5bab7ba01.png)

**Comment by jamesp-epcc** [comment]
Graphs for the last 3,670 jobs to complete on the grid. The pattern is similar to the previous ones except that there appear to be fewer jobs taking long periods of time to complete. This could be because the grid is quieter, or simply the nature of the instance catalogs currently being processed. These jobs are from WFD z band, all of which have now been run on the grid, although the outputs have not yet been uploaded due to the Cori maintenance outage.
![runtimes](https://user-images.githubusercontent.com/14821192/44338934-84bf6780-a477-11e8-859e-0c7672bbb937.png)
![waittimes](https://user-images.githubusercontent.com/14821192/44338935-84bf6780-a477-11e8-8bfb-7198749a27bc.png)

**Comment by cwwalter** [comment]
Do you have the ability to inspect a couple of the over 300min cases to understand whether that was some grid thing that was causing the data transfer to be slow or final reporting issue that made the run time seem long or whether imSim itself was really a few times longer than average in that case?

The sky time should basically be fixed so it would be useful to learn about those jobs if they really repeatably take longer.

**Comment by jamesp-epcc** [comment]
Graphs from about 13,000 jobs (approximately 4 days' worth). Not much change from previous distributions.
![runtimes](https://user-images.githubusercontent.com/14821192/44650855-ab355380-a9df-11e8-9a2c-aef5b5fe1885.png)
![waittimes](https://user-images.githubusercontent.com/14821192/44650856-ab355380-a9df-11e8-9a83-64792a402d2d.png)

**Comment by katrinheitmann** [comment]
@jamesp-epcc Since this set-up has now being replaced by something rather different, I think we can close this issue. If you think it should be still open, feel free to reopen it and update it.

Issue summary: these were the logs for the grid runs for run 1.2. For Run 2.1 which is running Y6/Y7 and beyond on the grid, a new set-up was developed to obtain better throughput. This new set-up is documented in the DC2 main paper.
