### ISSUE TITLE
Make a reduced 1.2i knot vs no-knot comparison

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2-production#182]
Run 1.2i will be done with the same instance catalogs as 1.2p.

But in run 2.0i we will turn on the star formation knots added by @EiffL.  So, we would like to also do a comparison run with at least a few focal planes (so as to get good statistics) of the same sources with and without knots.

When we get the test runs squared away on the UK gridPP and things look good, then we should schedule these too.  (CC: @jamesp-epcc).

**Comment by katrinheitmann** [comment]
@cwwalter Hi Chris, I guess this can be closed? Thanks!

**Comment by cwwalter** [comment]
Yep.  

Closed by https://github.com/LSSTDESC/imSim/issues/131
