### ISSUE TITLE
Explore Performance of access to coadd catalogs

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#190]
1. Identify trivial, moderate, and worst-case use case examples.
2. Measure performance on 
    a. single patch
    b. a single tract
    c. the full dataset
3. Record data sizes of each of the above a, b, c.
4. Determine if performance considerations mean we should generate a static file that contains a restricted set in columns.
5. Look into again using full `tables` functionality to write HDF5 files so that they can be read by column efficiently.  This was previously not possible because of an error trying to write the thousands of columns in our full coadd catalogs.  This is #158 

@EiffL will run on HSC products
@wmwv will run on DC2 Run 1.1 products

**Comment by yymao** [comment]
@wmwv In the same notebook you mentioned 
> In practice the GCRCatalog reader does need to read through all of the metadata in the HDF5 files to figure out what's in there and available. 

This is true because I am not sure if it is OK to assume that different tracts all have the same set of native quantities. If we can assume so, at `init` the reader only need to read one tract file, which can significantly save the time.

**Comment by EiffL** [comment]
I would vote for that. The merge tract script could ensure that the data is
consistent. It's painful to wait 45s to load the catalog, going to get
worse for dc2

**Comment by yymao** [comment]
Indeed, during the early phase of the coadd reader development, I've noticed that different tracts have different columns. If we can make sure the merge tract script guarantees that different tracts will have the same set of columns, the reader can change accordingly (I'll add an option for this now).

**Comment by yymao** [comment]
Oops, actually, the reader also needs to know the patches in each tract, unless we can also assume that the available patches in each tract are identical. Can we?

But at the core of this issue is that the hdf5 file is saved in the `fixed` format, which makes accessing available patches and columns taking longer than it should (@wmwv's point 5 and #158).

**Comment by wmwv** [comment]
@yymao Yeah, the performance functions are still a work in progress (I knew that function wasn't right). Thanks for the tips.I would in particularly like to understand the performance difference of when to use the iteration vs. a merged treatment.

**Comment by wmwv** [comment]
No, the patches available will differ because edge tracts will be only partial.

I'd rather keep the current behavior of not loading in a filter if if doesn't exist for that tract+patch, which creates different numbers of columns.

**Comment by yymao** [comment]
@wmwv indeed, without `return_iterator=True`, GCR will automatically concatenate the arrays from different chunks (or patches, in the case of the coadd catalogs). But depending on the use case, sometimes an iterator is more desirable. 

Note that, while the current implementation of the coadd reader does know the different available patches from different tracts, it doesn't do the same for the missing columns. The reader actually uses the *union* of all columns from all available tracts as the set of all available native quantities.

**Comment by wmwv** [comment]
@yymao Ah, so it would be fine to assume that all possible columns are available.  But the problem is determining when you know that all possible columns have been read in.

**Comment by wmwv** [comment]
I agree that #158 will likely be key here.  My plan is to first develop some specific metrics so that we can clearly demonstrate this.  @EiffL @yymao Do you have any good suggestions for somewhat interesting expensive things to do?

**Comment by yymao** [comment]
But wouldn't we need a `table` format hdf5 to compare? @wmwv

**Comment by wmwv** [comment]
We of course need both 1. performance metrics and 2. different data storage to test those metrics against.

**Comment by EiffL** [comment]
Sorry if I missed some of this discussion, but as with any database, the
catalog needs to have a fixed schema. Perfectly acceptable in my opinion to
have a first pass over all input files in the merge tract script to
determine all possible columns, and just have a way of saying data is
missing

**Comment by wmwv** [comment]
@yymao But I hear your point that you're arguing that basically all of column-based data access is just the HDF5 format and if we can get this to be `table` instead of `fixed` everything gets better.

**Comment by wmwv** [comment]
@EiffL I'm not sure if I agree or disagree, but for this present issue I'd like to focus on writing the performance tests that we can then use to demonstrate if a particular choice matters or now.

**Comment by yymao** [comment]
@wmwv @EiffL sorry so many different topics here... 

1. Let's say if Tract 1 has u-band but Tract 2 doesn't. The current behavior is the following: GCR will tell users u-band exists, and when the user tries to load u-band, GCR will load u-band from Tract 1, and creates an array of nan for Tract 2, and then concatenate them for the user. I believe this addresses the issue @EiffL mentioned.

2. However, in order to do (1), GCR needs to know the *union* of all available columns. Hence the current implementation go through all available tracts to find which columns are available in each of them  and take the union. This is not ideal but it's safe. If we don't want to do that, we need to make sure all tract files have the same set of columns. 

3. In principle (2) should not take too long, but because currently the hdf5 file are in the `fixed` format, loading the available columns takes longer. This is the part @wmwv says we should test (cf #158).

**Comment by wmwv** [comment]
@yymao I've generated two derived data products:
1. 'trim_' files that only include the columns used by the GCRCatalogs non_native quantities.
2. 'table_trim_' files that use the `format='table'` HDF5 format.

These are available on Cori in the standard place:
`/global/projecta/projectdirs/lsst/global/in2p3/Run1.1/coadd_catalog/`

**Comment by wmwv** [comment]
@yymao 
I can successfully read the `trim_` files by loading the catalog with a different `filename_pattern`.  But reading the `table_trim_` files triggers an error:

Here's the full output, but it's basically something that failed when reading in the dataset.

Can you think of anything in particular that might be different about the `format='table'` files?  They read in directly to Pandas fine.

```
gc_onetract_table_trim = GCRCatalogs.load_catalog('dc2_coadd_run1.1p_tract4850', {'filename_pattern': 'table_trim_merged_tract_4850.hdf5'})
```
```
/usr/local/lib/python3.6/site-packages/GCRCatalogs/dc2_coadd.py:219: UserWarning: table_trim_merged_tract_4850.hdf5 has incorrect hdf5 format; skipped
  warnings.warn(warn_msg.format(os.path.basename(fpath)))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-3045d3e588ff> in <module>()
      1 gc_onetract = GCRCatalogs.load_catalog('dc2_coadd_run1.1p_tract4850', config)
      2 gc_onetract_trim = GCRCatalogs.load_catalog('dc2_coadd_run1.1p_tract4850', trim_onetract_config)
----> 3 gc_onetract_table_trim = GCRCatalogs.load_catalog('dc2_coadd_run1.1p_tract4850', table_trim_onetract_config)

/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages/GCRCatalogs/register.py in load_catalog(catalog_name, config_overwrite)
    167         config.update(config_overwrite)
    168 
--> 169     return load_catalog_from_config_dict(config)
    170 
    171 

/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages/GCRCatalogs/register.py in load_catalog_from_config_dict(catalog_config)
    118     return import_subclass(catalog_config['subclass_name'],
    119                            __package__,
--> 120                            BaseGenericCatalog)(**catalog_config)
    121 
    122 

/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages/GCR.py in __init__(self, **kwargs)
     59     def __init__(self, **kwargs):
     60         self._init_kwargs = kwargs.copy()
---> 61         self._subclass_init(**kwargs)
     62         self._native_quantities = set(self._generate_native_quantity_list())
     63 

/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages/GCRCatalogs/dc2_coadd.py in _subclass_init(self, **kwargs)
     97         if not self._datasets:
     98             err_msg = 'No catalogs were found in `base_dir` {}'
---> 99             raise RuntimeError(err_msg.format(self._base_dir))
    100 
    101         bands = [col[0] for col in self._columns if len(col) == 5 and col.endswith('_mag')]

RuntimeError: No catalogs were found in `base_dir` /global/projecta/projectdirs/lsst/global/in2p3/Run1.1/coadd_catalog
```

**Comment by yymao** [comment]
@wmwv the current reader does not work on `table` format directly, as the metadata reading part is designed specifically for `fixed` format. 

For the performance test, we probably don't need a reader, do we? But I can work on the reader to make it work on `table` format.

**Comment by wmwv** [comment]
The tests should be as the user would use it, which means it should work in GCRCatalogs.

Clearly doing direct access to the file is an informative proxy and I'm running some right now.

**Comment by yymao** [comment]
Okay. The current coadd reader was optimized for the fixed format. I'll work on a version that is optimized for the table format, but it'll take some time for development.

**Comment by wmwv** [comment]
Merged to master.
