### ISSUE TITLE
Feasibility of magnification of SNe, lensed SNe/AGN?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2-production#2]
@rbiswas4 @jbkalmbach @danielsf The DC2 input catalogs will include a shear (gamma) and convergence (kappa) for each galaxy, including host galaxies of SNe and AGN. Do you foresee any problems applying these as magnification and shear to each SN and sprinkled lens system? Or can we go ahead and plan on including these weak lensing effects on the time domain targets?

**Comment by cwwalter** [comment]
My recollection from the meeting at SB was that we need an upgrade to the CatSim infrastructure to handle lensed SN.

**Comment by drphilmarshall** [comment]
@danielsf What would it take to apply a lensing magnification to each SN realized in/by CatSim? The input catalog will provide the convergence and shear at the host galaxy position, from which the (small) magnification can be calculated (approximately). The result will be an achromatic shift in all magnitudes - easy to apply?

The SL objects can be computed to have the right weak lensing shear and convergence, during or before the sprinkling process. I'm not sure this is vital to include but @tcollett and @dannygoldstein can advise. I guess if you know the WL effect on each source galaxy (AGN or SN host), you can include this (approximately) in the simulation of the lensing. Easy to do? Worth it?

**Comment by danielsf** [comment]
@drphilmarshall What you describe should be pretty easy to apply.  We can just add a method to the catalog-generating classes to add lensing magnification to the magnitudes before writing them to the catalogs.

**Comment by cwwalter** [comment]
October of 2017 was so long ago :) 

@drphilmarshall is this squared away now?

**Comment by katrinheitmann** [comment]
@danielsf @linan7788626 Quick question: did we do this in the end, are we still planning to do this in DC2, or is this a DC3 item? We should either update, move, or close this. Thanks a lot!

**Comment by danielsf** [comment]
The sprinkler applies the normal DC2 lensing parameters (i.e. the gamma and kappa parameters from the shear map that Patricia provided with cosmoDC2) to the strong lensing systems.  If I interpret Phil's original ask correctly, that means that "no; we did not end up doing this."

**Comment by katrinheitmann** [comment]
@drphilmarshall Can you confirm Scott's conclusion and either close the issue or move it to DC3 or ...? Thanks a lot!

**Comment by linan7788626** [comment]
Hi @katrinheitmann , sorry for my late reply, as far as I know, we did not do this for DC2. 
I suggest we move it to DC3, since, to involve external magnifications properly, we have to calculate the strong lensing signals specifically but not just match OM10.  It is the next step of the Sprinkler.

**Comment by drphilmarshall** [comment]
Thanks @linan7788626 - I agree, let's apply the additional (external) magnification next time, in whatever DC3 simulations we do. I don't think not having it will make a big impact on the SL DC2 projects. Closing!
