### ISSUE TITLE
Add NERSC Jupyter-Dev set up instructions to each Notebook header

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#206]
Add the following to the front cell of each Notebook:

"""
To set up your NERSC environment, please follow the instructions available here: https://confluence.slac.stanford.edu/display/LSSTDESC/Using+Jupyter-dev+at+NERSC
"""

**Comment by yymao** [comment]
Use the short URL instead in case someone changes the title of that page in the future

**Comment by yymao** [comment]
https://confluence.slac.stanford.edu/x/1_ubDQ

**Comment by wmwv** [comment]
This was done for the Tutorials notebooks.
