### ISSUE TITLE
Review of LSST_Stack_matching_code.ipynb

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/DC2-production#209]
This issue is meant to track the review of [LSST_Stack_matching_code.ipynb](../blob/master/Notebooks/LSST_Stack_matching_code.ipynb) owned by @jchiang87.

I was able to run the notebook end to end without any issues. Reading through, it looks like an important and well documented investigation into truth matching. A few minor suggestions:
* Stupid question first: what does `DRP` stand for?
* I'm a bit surprised that only a bit more than half of the galaxies were matched. I had considered 24.5 to be a relatively bright magnitude threshold for DC2, but maybe I'm mistaken. Obviously, it's not the purpose of this notebook to dive into this in detail, but a quick comment if you know off hand (something to match the "Is this what you would expect?" after Cell 9).
* Would it be better to show 2D histograms rather than scatter plots for the two lower panels in Cell 12? I'm not sure what to think about the large tail of outliers with `|r_gc - r_dp | > 1.0` (and hard to tell relative abundance in scatter plot).
* The last two cells are printing long lists of catalog properties. Not sure if this is desired, or if it's enough to truncate this after a few quantities. On the other hand, maybe it's useful as searchable documentation?

**Comment by bechtol** [comment]
* I like that this notebook shows how to create minimal table schema and append columns, as well as select a subset of rows from a table

* Given that this is a tutorial, I would recommend to spell out acronyms, e.g., what is "GCR"? I think `DRP` is referring to the "Data Release Products"

* In the class definition for `RegionSelector`, the coordinates
`protoDC2_ra = 55.064
protoDC2_dec = -29.783`
appear without any explanation. Where did these come from?

* Similarly, when selecting "Sources or Objects", there are hard-coded values for the dataids form visit,raft, sensor number / tract,patch . I wonder how someone would know how to get these dataids in more general cases. Maybe just a sentence to explain how these were retrieved would be helpful. I understand that these are details, but if someone wants to do more general investigations, it is helpful to know where this information could be retrieved.

**Comment by katrinheitmann** [comment]
@jchiang87 Can you take a look at this and see if it can be finalized and closed? Thanks!

**Comment by jchiang87** [comment]
This notebook was moved to the `DC2-analysis` repo and reviewed and merged there: https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/matching_stack.ipynb
