### ISSUE TITLE
LICENSE for DC2 scripts, notebooks

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2-production#217]
We need a LICENSE for this public repo. DESC-standard modified BSD? Full disclosure: I think the tutorial notebooks will be of interest to folks outside DESC, even at this early stage - so they will need guidance on how to work with them when copying and adapting. cc-ing data access afficionados @wmwv @boutigny @yymao @cwwalter for comment (and noting that Michael is also on the Pub Board).

**Comment by wmwv** [comment]
I agree with three-clause BSD.

**Comment by yymao** [comment]
Three-clause BSD is fine.

**Comment by yymao** [comment]
Question: should we add the license to this repo, or just the Notebooks directory?

**Comment by wmwv** [comment]
The whole repo.

I think it's confusing to have a difference license for different parts of the repo.

**Comment by katrinheitmann** [comment]
So what needs to be done to close this issue? (I think agreement has been reached ...) Thanks!

**Comment by yymao** [comment]
See PR #224. @drphilmarshall is working on it.

**Comment by katrinheitmann** [comment]
@drphilmarshall This is pretty urgent: @sethdigel is reminding us that we need a license for releasing the cosmoDC2 data. Can you help with this, point us in the right direction? Thanks!!

**Comment by drphilmarshall** [comment]
Regarding suitable license and README notes for the DC2-production repo, what I had in mind for #224 was more along the lines of what we need to be doing for all public DESC repos in which unreleased products are being developed, so a bit different from what you are asking about for an actual data release.

For the CosmoDC2 catalog, assuming a principle of maximizing DESC member visibility and scientific reproducibility through liberal licensing with maximum attribution, the Creative Commons license chooser tool at https://creativecommons.org/choose/ suggests we go with CC BY-SA 4.0, which you can read about here: https://creativecommons.org/licenses/by-sa/4.0/  (There's a link to the actual license file there too.)  I'd suggest the attribution URL be a landing page on the DESC public website that also provided this license, some citation guidelines, other README-like notes, and the link to the data download. Most of the (small) DESC datasets on our Zenodo site at https://zenodo.org/communities/lsst-desc have this license, too.
