### ISSUE TITLE
Explore using Firefly on NERSC

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#229]
1. Prototype an interactive set up
2. Plan what it would take to be a maintained service.

**Comment by katrinheitmann** [comment]
@wmwv Is this still actively under consideration? If so, can you update the issue, if not, close it? Thanks!

**Comment by wmwv** [comment]
It remains a long-term dream.  It would be nice and important to set up a full LSST Science Platform analog at NERSC, but will require some dedicated server infrastructure that we don't have and don't plan to have in the near future.

**Comment by katrinheitmann** [comment]
So there is a DC3 planning repo. Rachel suggested to (a) tag the issues that we will not do in the near future with Move to DC3 (I did that), (b) start an issue in the DC3 planning repo called "left over from DC2", then link to it there and close it in DC2.

Does that sound reasonable? Thanks!

On 4/12/19 9:56 AM, Michael Wood-Vasey wrote:

More broadly, I think this issue falls under the category of a number of issues that remain good ideas but we are not prioritizing. We shouldn't forget that we've already written down these issues. Where do you want to collect such things? Simply marking them as Closed makes them hard to find again. Keeping them as Open perhaps clusters a search for prioritized Open issues that we should work on.

**Comment by yymao** [comment]
There is a DC3 planning repo?

**Comment by katrinheitmann** [comment]
Yes -- not much in there yet. https://github.com/LSSTDESC/DC3-planning

**Comment by katrinheitmann** [comment]
We have moved this question into DC3 planning. During the DC2 era we had not enough resources to make this happen and want to follow up in the DC3 era. The DC3 planning github issue is linked here: https://github.com/LSSTDESC/DC3-planning/issues/1
