### ISSUE TITLE
What would it take to run a full LSST Science Platform at NERSC/IN2P3?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#230]
What would it take to run a full LSST Science Platform at NERSC/IN2P3 to serve DC2, DC3?

1. What do we need in hardware?
2. What do we need in access?
3. What is the timeframe for these pieces being available?
4. What do we need in interactive user data support?

**Comment by katrinheitmann** [comment]
@wmwv Do we need to keep this or is the one on firefly in DC3-planning enough to remind us? We could copy the four bullet points over to there if you think it's important. Thanks!

**Comment by wmwv** [comment]
I would say this issue is the more important issue to transfer to DC3-planning.  The Firefly is a subset of this.

**Comment by katrinheitmann** [comment]
Moved to DC3 issues.
