### ISSUE TITLE
Compute purity and completeness for stars, galaxies for DC2 Run1.1p

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#235]
1. [ ] Compare the Object (coadd) catalog with the truth catalog to calculate purity and completeness for star-galaxy identification as a function of magnitude.
2. [ ] Compute a variability metric and compare its additional distinguishing power.
[Maybe wait for Run 1.2]
3. [ ] Compute a seeing-weighted variability metric to identify stars vs. galaxies by how their magnitude changes under different seeing.
  - May need to include some systematic stochastic intrinsic variability parameter for each of stars and galaxies (AGN?).

**Comment by johannct** [comment]
@wmwv  This is riminiscent of a question that arose when we modified the maxFootprintArea attribute recently for 1.2p calexp processing studies. It sounds that this is issue is one path forward to checking that in the end we get convincing purity and completeness aat calexp and coadd level respectively. Is this issue still open by oblivion, or did the work not complete?

**Comment by wmwv** [comment]
Yes, the work in this issue remains to be done.

**Comment by katrinheitmann** [comment]
@wmwv Since this issue is about Run1.1, I assume it can be closed because the work would be done now on a newer datset? If that is not correct, feel free to reopen.

**Comment by wmwv** [comment]
This remains a thing that should be done in general.  It's not something that should be done for Run 1.1p or Run 1.2.

I fear that if we close this issue without opening a new one, we will forget that this needs to be done.

@katrinheitmann Would you rather
A) this issue be closed a new one opened for Run 2.1i?
B) this present issue to be edited to reflect doing the work for Run 2.1i?

**Comment by katrinheitmann** [comment]
I prefer a new one for Run 2.1. Thanks!

**Comment by wmwv** [comment]
Very good!  Done, and I realized that creating this new issue under `DC2-analysis` might be more appropriate.

https://github.com/LSSTDESC/DC2-analysis/issues/91
