### ISSUE TITLE
Get Dask working at NERSC to analyze DC2

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#237]
Get Dask working at NERSC to analyze DC2.

[x] Single-node
[ ] Job queue multi-node
http://dask-jobqueue.readthedocs.io/en/latest/configurations.html#nersc-cori

**Comment by wmwv** [comment]
This work has ended up continuing in #190 
In brief, I have Dask working in single-node and job queue multi-node (using 'debug' queue) on Cori.  It works but is no faster.  Follow #190 for more.

**Comment by heather999** [comment]
@wmwv Where is the notebook associated with these tests?  at this point, I just have some curiosity.  Was there any difference in using SCRATCH? I looked into the details of using the Burst Buffer, and plan to write those up. I imagine that may be generally useful outside of this specific work.

**Comment by wmwv** [comment]
The Notebooks are in the respective branches:

https://github.com/LSSTDESC/DC2-production/blob/issues/190/Notebooks/DC2_Catalog_Performance.ipynb
https://github.com/LSSTDESC/DC2-production/blob/issues/237/Notebooks/object_catalog_performance_dask.ipynb

**Comment by wmwv** [comment]
@heather999 #190 was just merged to master, and I renamed the Notebook above.  So you can look now in

https://github.com/LSSTDESC/DC2-production/blob/master/Notebooks/object_catalog_performance.ipynb

**Comment by wmwv** [comment]
Closed by #276
