### ISSUE TITLE
Store object catalogs in "one column per group" format (i.e., not pytables)

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-production#242]
Currently the data structure for the object catalog (which is stored in hdf5 file using pandas/pytables) is the following:

- tract [a single file]
  - patch 0,0 [a single table in a group] 
  - patch 0,1 [a single table in a group]
  - patch ...

With this structure, even when a user request only a small subset of columns, we still need to load the whole table into memory. 

Since in most use cases, only a small subset of columns are needed. A different data structure can improve the data access efficiency. In particular:  

- tract [a single file]
  - patch 0,0 [a single file OR a group]
    - column A [a group]
    - column B [a group]
    - column ...
  - patch ...
    - column ...

To further help with the data access/load efficiency, we can also predetermine all the column names (A, B, ...) and store them a separate place, so that the reader will not need to visit all groups to determine available columns. 

If we store each patch as a single file, the reader can find out all available tracts and patches by `os.listdir`, without even opening any file at initialization. 

In fact, if we do store each patch as a single file, I don't think we even need hdf5. For each patch, we can do
```python
np.savez('object_{}_{}.npz'.format(tract, patch), A=col_A_data, B=col_B_data, ...)
```
It's lightweight and only requires numpy, but I haven't tested its performance.

**Comment by wmwv** [comment]
@yymao I'd like to split out the providing schema to GCRCatalogs reader to its own ticket.  I've created #243 in this repo to produce the [gcr-catalogs/issues/169](gcr-catalogs/issues/169) one to read it.

**Comment by wmwv** [comment]
I'd like to mark this issue as closed.  With the schema now available and the further availability of Parquet files of the DPDD formatted Object Tables.

@yymao Do you agree?

**Comment by yymao** [comment]
Sure. I'm closing this now.
