### ISSUE TITLE
Longer term storage of Run1.2i images at NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#244]
Currently the data produced (currently 800 GB) using the UK grid is stored at NERSC on Cori SCRATCH: /global/cscratch1/sd/jamesp/DC2output
Files left untouched for 12 weeks are subject to purging. James P reports, the files were originally copied over on 9th July, so we have some time.
For the short term, we can make sure that these files are accessed so they are not purged. We can also tar/bzip the files and place them under projecta or into HPSS for safe keeping.

How long do we want these images to be immediately available on SCRATCH? Into December perhaps?
Is it appropriate to save these files long term in HPSS?

**Comment by katrinheitmann** [comment]
What is the reason to not put them into project space (after all we 
bought the storage for the image simulation work)? Also, I have never 
fully understood what accessing means (besides touch), just reading them 
in in my case was not enough in the past ... The data is definitely 
important since we use it for a lot of validation. So it should be 
stored for long term.

Thanks! Katrin

**Comment by heather999** [comment]
I'm hesitant to just copy them over to the project area due to concerns about utilizing too much of our inode quota.  The phosim infrastructure files we currently store on the projecta area have consumed a lot of the inodes. Tom and I are working to fix that by tar/bzipping all those files. That needs to be fixed first before I copy any other large set of files.
Once that is done, we may still want to tarball/bzip the image simulation files to save on space and inode use - but obviously to do any useful work, the files will need to be periodically copied and extracted back into SCRATCH.
I gather all the data for this round will be available ~Aug10th, so we should plan to be ready to make a copy on projecta by that time. 

That bit concerning about reading not being enough to avoid purging is a concern. I will look a little more deeply into that.

**Comment by awborgland** [comment]
How difficult is it to get our inode quota increased? Just for peace of mind ....

**Comment by salmanhabib** [comment]
Are we running into a problem with too many small files?

**Comment by heather999** [comment]
@awborgland we can ask, but in this case it is more appropriate that we store these phosim setup files as tarballs to help alleviate the issue, as @salmanhabib is correct - this is just an example of having too many small files.  We have already had some interactions with NERSC about our inode quota, where possible, I want to make sure we are doing all we can up front before poking for more.

**Comment by wmwv** [comment]
The size of our files is completely reasonable.  HPCs have been trying to tell me for two decades that my file sizes are "too small".  But my file sizes are exactly the reasonable scientific unit.  They should adjust to their users and recognize that they should allocate more space for inodes.

**Comment by salmanhabib** [comment]
@wmwv Parallel file systems are not designed to work with very large numbers of small files. Most users at HPC centers have large files or have aggregation techniques to deal with large numbers of small files. All large (non-grid) machines that we will have access to will be like this.

**Comment by wmwv** [comment]
Yes, I know.  I'm familiar with the technical issues.  But it drives me nuts as a user experience.  25 MB is a totally reasonable file size.

If we have millions of 1kb files, then sure, yes we should compromise and not do that.

**Comment by wmwv** [comment]
But to leave my ranting aside and contribute more productively:
* Thanks, Heather and Tom for keeping on top of all of this.
* These should definitely live on /projecta (just to redundantly repeat what Katrin already said)
* We should definitely save all of this to HPSS.  I'm not deeply tied to exactly in what chunk size that is done (perhaps by focal plane?), but a user should be able to figure out what they need by looking at path names in the HPSS file directory.

**Comment by salmanhabib** [comment]
Clearly any material that is archival should be bundled up just like Heather et al are doing. At some point, we need to ask ourselves what our storage load and file size distribution would look like. I guess we in CI should try to figure this out.

Use of data containers could help too (I have had vague discussions with the HDF people about this, maybe we can attempt something more definitive?).

**Comment by jchiang87** [comment]
I'd like to keep them in some form at least until we've done some visit-level validation of the DM outputs for a substantial portion of the i-band ANL data.

**Comment by heather999** [comment]
Just an update on the inodes, the tarball and removal of the expanded Run1.2p SEDs is complete, and the inode use has dropped dramatically as hoped:
prjaquota lsst:
                  ---------- Space (GB) ---------     ------------- Inode --------------
Project             Usage      Quota    Percent          Usage       Quota     Percent
---------------   ---------  ---------  ---------     ----------  ----------  ----------
lsst                 194431    1024000         19       22960805    50000000          45

**Comment by heather999** [comment]
The UK Run1.2i data in `/global/cscratch1/sd/jamesp/DC2output` has been copied over to /global/projecta/projectdirs/lsst/production/DC2_ImSim_UKTest parallel with the DC2_ImSim area to avoid confusion and also with the assumption that this UK data is temporarily housed in this location and will ultimately be moved to HPSS. One directory was inaccessible `/global/cscratch1/sd/jamesp/DC2output/old `- which I assume is not needed.  For now I've left the tarballs uncompressed as they were on CSCRATCH.   That's easily revisited, and ultimately this data will be compressed before being stashed in HPSS.

**Comment by katrinheitmann** [comment]
@heather999 Has this been sorted out or do you need more input? Thanks!

**Comment by heather999** [comment]
And now `/global/projecta/projectdirs/lsst/production/DC2_ImSim_UKTest` has been transferred to HPSS under `/home/projects/desc/DC2_ImSim_UKTest`
