### ISSUE TITLE
Handling WFD and UDDF fields in DC2

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/DC2-production#247]
At the moment we have no mechanism to handle separately the `WFD` and `UDDF` fields. Looking how HSC is doing, we could store this information as a metadata "OBJECT" in the raw data headers written by `phosim`. Then with a simple change in the `LsstCamMapper` we could read this metadata information and persist it in the butler directory tree.

This information is not present in Run1.2p, the only place where the field is referenced within the raw data files is in the `SEDDIR` metadata:
```
SEDDIR  = '/global/cscratch1/sd/descpho/Pipeline-tasks/DC2-R1-2p-uDDF-u/000119/'
```

If we do this modification, it will be possible to specify the field name through the `dataid`

What do you think ?

**Comment by egawiser** [comment]
One minor note:  We have realized belatedly that it's better to refer to these as WFD and DDF.  The "u" in "uDDF" doesn't add meaningful information but can cause confusion - our simulated DDF is smaller than an LSST FOV but otherwise is within the range of survey strategies envisioned for LSST Deep Drilling Fields.

**Comment by wmwv** [comment]
In principle, I don't think it makes sense to associate a specific fixed program to each observation.  LSST will execute a strategy to fulfill a list of goals.  A given Visit can satisfy a variety of them.

In practice, and for our simulations, I agree that it will be very helpful and useful to keep something like "PROGRAM", "FIELD", "SURVEY", or "OBJECT" that says why the image was generated.  Particularly given the way we're doing the simulations it is the case that each image was generated for a specific traceable reason.

**Comment by boutigny** [comment]
@wmwv so if I understand correctly, you think that it is better to coadd and use whatever image is in a given field independently of the observation program, rather than making different sets of coadd for `WFD` and `DDF` ?

**Comment by wmwv** [comment]
I think for our simulation purposes it's fine to treat them separately.  But I think in actual operation Visits won't be so separate.

But I agree that one useful thing we should post somewhere in the DC2 pages is just a file of

```
visit,program
23490876,WFD
23490900,WFD
12908669,DDF
...
```

**Comment by egawiser** [comment]
That seems like it would suffice.  Because the DDF is in the corner of the DC2 region, we could also make a single co-add and then split it up into the very deep DDF and the "normal depth" WFD regions, losing only a tiny portion of the potential WFD area.  I don't see any reason to exclude "WFD" visits in the DDF region from the DDF coadd, although the added depth will be small.

**Comment by RobertLuptonTheGood** [comment]
FYI, the current LSST plan is not to have nice easy to handle visit IDs, but describe exposures by the tuple
	(instrument, controller, day, ID)
where ID is only unique within the day.
E.g.
	(MC, O, 20220820, 1234)

The first two are irrelevant for DESC (I hope!), but the last two replace the visit.  This shouldn't make too much difference in practice, but please don't plan for a single int.

Reference:
https://confluence.lsstcorp.org/pages/viewpage.action?spaceKey=SYSENG&title=Image+naming+and+visit+definition+conventions

**Comment by wmwv** [comment]
> I don't see any reason to exclude "WFD" visits in the DDF region from the DDF coadd, although the added depth will be small.

Yes.  Thanks, @egawiser , for clearly articulating something I was stumbling over and failing to say above.

My logistical point was that one can also pass a list of visits to a processing step and get products that only result from the processing of those visits.

**Comment by katrinheitmann** [comment]
@boutigny @wmwv What is the status on this issue? My understanding is that we are handling DDF and WFD in the same way right now. Is it possible to write a concluding remark and close the issue? Thanks!
