### ISSUE TITLE
Update Static Lens images for new AGN host galaxies

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2-production#256]
@linan7788626 Since we are going to update the sprinkled galaxies with the new catalog we will need to generate a new set of host galaxy images, correct?

As soon as we have matched to a new extragalactic catalog @jbkalmbach will create the necessary catalog for @linan7788626 to generate the inputs needed to create host galaxy images that will run with the functionality being added into LSSTDESC/sims_GCRCatSimInterface

**Comment by mmtoys** [comment]
Hi @jbkalmbach , correct, if we update the catalog, we need to create the corresponding set of host galaxy images.

**Comment by linan7788626** [comment]
Hi @jbkalmbach , correct, if we update the catalog, we need to create the corresponding set of host galaxy images.

**Comment by danielsf** [comment]
I am going to close this issue.  We have generated catalogs of static lenses and I have tested that they are connected to the InstanceCatalog pipeline.
