### ISSUE TITLE
Run 2.0i: more adjustments to knotty galaxy morphology (for big/bright galaxies)

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/DC2-production#265]
This weekend some test images that were produced in preparation for Run 2.0i revealed some problems - see y-band image below:

![v12365_r22_s10_y_knots1_gal1](https://user-images.githubusercontent.com/1454906/45622432-f4624b80-ba51-11e8-8e43-b5f8840b5538.png)

This issue is about the galaxy that I’ve circled here.  As you can see, the knotty morphology distributes some of the knots outside the diffuse component of the galaxy.  Some digging by Francois @EiffL showed that the knots model, which was optimized to enable fainter galaxies to take on an irregular appearance without much of a disk (as could be appropriate at z~1), needs to have the knots flux fraction capped to avoid larger nearby galaxies looking, well, like the one I’ve circled.

To address this, we’ve capped the fraction of the disk flux that gets transferred to knots, multiplying the knots flux fraction by 0.5*[1 - np.tanh(np.log(size in arcsec/1.5))] in a post-processing step that modifies the instance catalogs.  This corresponds to preserving the knots flux fraction at its current value for galaxies below a size of ~0.8 arcsec, and  smoothly reducing it for larger galaxies.  Some preliminary tests revealed that this leads to more realistic morphology for larger nearby galaxies, with a clearly visible diffuse component in the area where the knots are present.

Comments and questions are welcome.

**Comment by jmeyers314** [comment]
Are all the knots the same flux?  (It appears that way in the image).  If so, can/should their individual fluxes be varied?

**Comment by sethdigel** [comment]
> Are all the knots the same flux? (It appears that way in the image).

Yes, they are.  Here is a log-scaled image of the same galaxy (reversed left-right for on-sky orientation).

<img width="703" alt="galaxy_knots" src="https://user-images.githubusercontent.com/6035835/45637341-16ae9600-ba5f-11e8-93fe-454ba0f65035.png">

**Comment by rmandelb** [comment]
Thanks for posting this, Seth.  Also: just to emphasize since it seems this caused some confusion on GitHub, the plot I posted *and* the one Seth posted are from before the correction that I described; they are what motivated that correction, not the result of it.

Here's an example from after an initial correction (not the final one, there was some more iteration after this):

![](https://files.slack.com/files-pri/T06D204F2-FCUBCSA0G/knot_fix_comp0.png)

I believe the right was some other galaxy before correction, the left is that same galaxy after correction.  You can see more of a diffuse disk component underneath the knots on the left.

**Comment by egawiser** [comment]
As some quick feedback, I'm at the LSST Cadence Hackathon with @yoachim sitting next to me.  We looked at the image Rachel posted and both think that the galaxy on the left looks plausible.  It still strikes us as a bit too lumpy for anything redder than the rest-UV, but that's a modest lack of realism, and it's a *huge* improvement versus the "instant Nature paper" image on the right.

**Comment by katrinheitmann** [comment]
@rmandelb @EiffL I think this issue is ready to be closed? We fixed everything here. Actually, it would be great if either of you could add a discussion about this into the DC2 paper: https://www.overleaf.com/project/5c783b15064426444792dd45 What do you think? Thanks a lot!

**Comment by rmandelb** [comment]
@katrinheitmann - I agree this can be closed; however, it's not clear to me where in the paper it should go.  It's not part of the extragalactic catalog (section 6.1) but it feels like maybe it deserves a new subsection in section 6?  Are there any other things that we do post-extragalactic catalogs as input to the image sims that isn't already captured in section 6?  For now, I've added a new subsection called "Additional modeling of static objects in extragalactic catalogs" (terrible name, I know, but it distinguishes it from the sprinkler stuff...) directly after 6.1 and made a note that @EiffL is the ideal person to write about the knots model.  Please feel free to move as you see fit.

**Comment by katrinheitmann** [comment]
Yes, Section 6 is perfect for this and a new subsection makes a lot of sense. And while the title of the subsection is maybe not pretty, it describes exactly what should be there.
