### ISSUE TITLE
HDF to Parquet conversion: need broader choice of engine

### ISSUE THREAD

**Issue by JulienPeloton** [LSSTDESC/DC2-production#270]
Currently the conversion from HDF to Parquet in `scripts/convert_merged_tract_to_dpdd.py` is done using fastparquet. Ideally, one would like to make optional the choice of engine (e.g. pyarrow is definitely a viable option), with fastparquet as default.

@wmwv If that's ok, I can propose the PR.

Julien

**Comment by JulienPeloton** [comment]
Actually, the same comment applies for the choice of the compression algorithm to use. Parquet currently offers: gzip (default), snappy, lzo, or uncompressed.

**Comment by wmwv** [comment]
I agree.  And in the immediate we can easily add those as command-line config options that get passed through.  If you'd like to submit a PR that would be great.

For your historical interest: the reason I specified `fastparquet` problem is that I couldn't get `snappy` installed on NERSC (just trying by myself -- I don't think this is insurmountable).  That meant that I had to specify the compression, but that meant I had to specify using `fastparquet`.  All of this could be generalized with the same defaults as currently there, as you suggest.

`pyarrow` is definitely a very likely future.

**Comment by wmwv** [comment]
Are there any specific incompatibilities in the files themselves?

**Comment by JulienPeloton** [comment]
OK, thanks for the history, it makes sense! I will go for the PR then.

Concerning incompatibilities in the files, I'm not sure I understand what you mean exactly.
Do you mean reading a set of mixed catalog files generated with different parquet engines? Or compression algorithms? Or do you have something else in mind?

**Comment by wmwv** [comment]
I meant whether you knew of any problems we might encounter with writing all of the files with one Parquet engine but reading it with another.

**Comment by JulienPeloton** [comment]
Good point, at first sight that can happen (especially concerning metadata, or supported data types).
On the bright side, the engine name is stored in the files, and can be retrieved.

For the dpdd files, I just created a file using one engine, and I was able to read it and get the same data using both engines. But I will keep an eye on it.

**Comment by JulienPeloton** [comment]
Resolved in https://github.com/LSSTDESC/DC2-production/pull/271.
