### ISSUE TITLE
Run jointcal

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/DC2-production#275]
In order to run jointcal on Run1.2 data we need to implement the following:

1. modify the primary fits header in order to include at least the `airmass`. At the moment several entries are present only in the extensions headers. I suggest to modify the raw file repackaging task (amplifiers --> ccd) in order to copy to the primary header any extension header entry which is common to all the amplifiers. 
2. modify `lsstCamMapper.py` to copy the relevant metadata to the `visitInfo` object
3. add the `joincal` specific entries in `policy/lsstCamMapper.py`
4. add a `jointcal.py` configuration file to the `config` directory.

2,3 and 4 are available in the branch u/boutigny/jointcal
The changes in `obs_lsstCam` should only be put into production once the primary fits headers have been updated

Once this is done, we will have to decide how to handle the quantities necessary to take correctly into account the refraction angle into jointcal (era...)

**Comment by katrinheitmann** [comment]
@boutigny @jchiang87 Has this all been solved or is there an update about what has been solved and what needs to be still resolved? Thanks!

**Comment by jchiang87** [comment]
I think everything has been resolved.   We've decided not to run jointcal on imsim data, and any lingering issues wrt photometry and astrometry are being followed up by DM at 
https://jira.lsstcorp.org/browse/DM-16226
https://jira.lsstcorp.org/browse/DM-18630
