### ISSUE TITLE
preliminary validation of 2.0i results

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2-production#278]
@jchiang87 asked me to take a look at the files at `/global/cscratch1/sd/jchiang8/desc/Run2.0i/output_ref_cat/rerun/jchiang/w_2018_39` and I am posting the results here:

I checked the single visit catalogs available in r-band and this is their footprint:

![image](https://user-images.githubusercontent.com/13971732/46827875-a0940b00-cd4e-11e8-8d93-a57d65bcaffd.png)

I believe that the underdense region is where we have stars but no galaxies are available (that part is out of WFD).

The sources look detected correctly:

![image](https://user-images.githubusercontent.com/13971732/46827931-bd304300-cd4e-11e8-9460-079ddc30ca10.png)

And there are no apparent biases in astrometry (for stars):

![image](https://user-images.githubusercontent.com/13971732/46827978-d933e480-cd4e-11e8-9f9a-40d12be056c7.png)

(The difference in shape between RA and DEC is because we are not at the equator)

Nor photometry (for stars):

![image](https://user-images.githubusercontent.com/13971732/46828010-f5378600-cd4e-11e8-82da-aa9ac1882f39.png)

![image](https://user-images.githubusercontent.com/13971732/46828035-07b1bf80-cd4f-11e8-9432-0704f6597f5f.png)

The size of the PSF looks correct (please ignore the galaxies in there since they're not matched to anything)

![image](https://user-images.githubusercontent.com/13971732/46828625-78a5a700-cd50-11e8-913a-df970298f1e7.png)

And it looks like brighter-fatter is present (zooming in that graph and computing the difference with respect to the average T):

![image](https://user-images.githubusercontent.com/13971732/46828633-80654b80-cd50-11e8-983c-eb4d546d5665.png)

I'll check the other bands and I'll try to check the galaxies' shapes soon.

**Comment by egawiser** [comment]
Thanks, @fjaviersanchez .  I like your plots but did not understand your analysis of the footprint underdense regions being "out of WFD".  The WFD is basically a rectangle on the curved sky, so it shouldn't have any zig-zag edges like that.  The explanation must be more subtle.

**Comment by fjaviersanchez** [comment]
@egawiser sorry for the confusing statement. Those zig-zaggy structures are the edges of the HEALPixels of the cosmoDC2 portions used for the image sims. I believe that the centers of those chips lie out of the WFD region and that the stellar catalog is queried with a different geometry than the galaxy catalog (that's why there are still stars but no galaxies).

**Comment by rmandelb** [comment]
Since it's just a single g-band visit with really bad seeing (-> fully atmosphere dominated) I would expect it to be an outlier in this respect.

But also, we should remember that within a visit, since the PSF has spatial correlations, we're not really seeing independent realizations of the PSF.  I suspect the 50th and 95th percentile criteria are more meaningful when collecting statistics across many independent realizations.

**Comment by rmandelb** [comment]
Also thank you for updating the plots to include the seeing and alt values - very helpful!

**Comment by jmeyers314** [comment]
Thanks very much @fjaviersanchez .  I think these look pretty reasonable for individual visits.  We know from the 1.2i analysis and discussion that the atmospheric component is pretty round, so I don't think the g-band visit (which, as Rachel points out is atmosphere dominated) is that surprising.  If anything, it's a little jolting to see the r-band visit with median ~0.055 (though not too jolting).

More statistics would be nice, but this looks encouraging.

**Comment by fjaviersanchez** [comment]
I can accumulate all of the r- and i-band visits available but they aren't that close to zenith (they are ~40-60 deg altitude) and we don't have many processed 2.0i visits yet (we have 1 r-band and 2 i-band as far as I know)

**Comment by fjaviersanchez** [comment]
Okay, I think we are done with this since we moved to Run 2.1i. Feel free to re-open as needed.
