### ISSUE TITLE
Improve Instance Catalog Generation

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/DC2-production#280]
This issue will track the progress on improving the efficiency in time and use of resources for generating the instance catalogs for Run 2.0. The decision has been made to solve the SED+dust mismatch between CosmoDC2 and ImSim/PhoSim by implementing Solution 4 (fit SED + Av +Rv and adjust magNorm to force agreement with cosmoDC2 observed magnitudes). The following is an edited  list of items that need to be worked on (including updates from comments further down in this issue)
1.  Generate SED lookup table for  cosmoDC2 disks and bulges (Fit all disks and bulges to SEDs and   magNorms and store that in a lookup table)
     - [ ] Code to do this (adapt Scott’s SED, Av and Rv fitting)
     - [ ]  Lookup-table organization (healpixel, galaxy-id, SED_id, Av, Rv, 6x magNorm)
     - [ ] Changes to CatSim 
     - [ ] Small-scale test needed?
     - [ ] Who can work on this?

2. Move UW database to NERSC or reconfigure to allow more concurrent connections. (Enables parallelization  of star catalog generation)
    - [ ] Can number of connections be increased?
    - [ ] How difficult would it be to move it to NERSC?
    - [ ] Who can do this?

3. Speed up AGN generation 
    - [ ] Done but needs to be tested
4. Incorporate the knot catalogs
5. Add strong lenses and SNe
6. Change output format to binary. Is on-the-fly generation feasible/desirable? 
    - [ ] Refactor output to write binary file (hdf5 for example)
    - [ ] Agree on output format
    - [ ] Changes to CatSim (who can do this?)
    - [ ] Changes to ImSim (who can do this?)
    - [ ] Organize output to Include chip information as hdf5 group
    - [ ] Other useful information that should be included?
7. Other
    - [ ] Profile of CatSim code: have we addressed the main sources of slow-downs?
    - [ ] Is there anything else that can be done at the instance-catalog-generation step to speed up ImSim? (eg Jim suggested including the chip information in the output file as an hdf5 group. Are there any other examples like this?)

**Comment by jchiang87** [comment]
I'd like to suggest one more possible item:
7. Chip-level selection/assignment in the instance catalogs.  This will enable imSim to avoid having to ingest the full field-of-view instance catalog if it is simulating a subset of the CCDs, and it will also help speed up the initial ingest for restarts from checkpoints.

**Comment by danielsf** [comment]
I think item (1) should actually just be: "Fit all disks and bulges to SEDs and magNorms and store that in a lookup table somewhere."  That will allow us to both speed up and reduce the memory footprint of InstanceCatalog generation.

Explanation: fitting the SEDs requires loading the 30 tophat magnitude columns into memory, which I suspect is the biggest part of the InstanceCatalog generation memory footprint.  If that goes away, I think we will be able to fit more than 2 InstanceCatalog generation jobs onto a node at once.

**Comment by danielsf** [comment]
@jchiang87 I assume you that the chip-level selection is going to need to use the magnitude-dependent scheme that you are using in ImSim?

**Comment by danielsf** [comment]
I believe (3) was achieved in this PR

https://github.com/LSSTDESC/sims_GCRCatSimInterface/pull/67

though I only tested it on a small job, generating 4 full focal plane InstanceCatalogs at once.  They completed in ~ 5 hours

**Comment by jchiang87** [comment]
> @jchiang87 I assume you that the chip-level selection is going to need to use the magnitude-dependent scheme that you are using in ImSim?

What I had in mind was just running the equivalent of the [`_chip_downselect`](https://github.com/LSSTDESC/imSim/blob/75cb59883364acb180c2c7534b4c25271d93fcf5/python/desc/imsim/imSim.py#L423) function at the instance catalog generation level, and writing out the lists of object entries for each sensor separately, e.g., as a different group in an hdf5 file, so that imsim could just grab the list for the desired sensors directly.

**Comment by evevkovacs** [comment]
@jchiang87 @danielsf  For 6) and 7), outputting the instance catalog as say, an hdf5 file, and having one group for each chip as stated above seems like a good solution. Can we get CatSim/ImSim people together to
1) agree on the output format
2) identify people to work on the necessary modifications to CatSim and ImSim
What would be the time-scale for this?

**Comment by danielsf** [comment]
For those who are interested: I ran a full focal plane InstanceCatalog generation job last night on one of the Edison login nodes.  The whole job took about 8 hours to complete.  I am attaching the result of `cProfile` if people want to investigate the bottlenecks.  Right now, the biggest botteleneck is the SED fitting code.  We already have plans to address that by creating an SED lookup table that can be stored at NERSC and consulting by subsequent InstanceCatalog generation jobs.

[profile_login_277065.txt](https://github.com/LSSTDESC/DC2-production/files/2489199/profile_login_277065.txt)

**Comment by katrinheitmann** [comment]
@danielsf I was wondering if this issue should be either closed or some of the items should be moved somewhere else? I think the only item 6 is not done. What do you think? Thanks!

**Comment by danielsf** [comment]
Yeah.  We should probably close it.  Only (6) and Jim's suggested (7) are not done.  Both, I think, are out of scope until the redesign of ImSim begins.  Probably that work should just be folded into a "implemented binary InstanceCatalogs" issue under ImSim.
