### ISSUE TITLE
MergeConflictWarning on Run1.2p

### ISSUE THREAD

**Issue by plaszczy** [LSSTDESC/DC2-production#283]
not sure it is a big issue but accessing Run1,2p data one gets

ARNING: MergeConflictWarning: Cannot merge meta key 'NOISE_SEED_MULTIPLIER' types <class 'int'> and <class 'list'>, choosing NOISE_SEED_MULTIPLIER=[1, 1, 1, 1, 1, 1] [astropy.utils.metadata]
WARNING: MergeConflictWarning: Cannot merge meta key 'NOISE_SOURCE' types <class 'str'> and <class 'list'>, choosing NOISE_SOURCE=['measure', 'measure', 'measure', 'measure', 'measure', 'measure'] [astropy.utils.metadata]
WARNING: MergeConflictWarning: Cannot merge meta key 'NOISE_OFFSET' types <class 'float'> and <class 'list'>, choosing NOISE_OFFSET=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0] [astropy.utils.metadata]
WARNING: MergeConflictWarning: Cannot merge meta key 'NOISE_EXPOSURE_ID' types <class 'int'> and <class 'list'>, choosing NOISE_EXPOSURE_ID=[317792259, 317788291, 317796611, 317786116, 317790212, 317786180] [astropy.utils.metadata]

**Comment by wmwv** [comment]
This was a type specification error in defining the merge logic for metadata in the AstroPy tables.

The completion of #317, which switched over to doing this in Pandas also fixed this issue as a side-effect.
