### ISSUE TITLE
add dedicated scripts to write FITS/Parquet objects catalog output

### ISSUE THREAD

**Issue by plaszczy** [LSSTDESC/DC2-production#293]
currently convert_merged_tract_to_dpdd.py (tries to) write 3 data format outputs: HDF5, FITS, Parquet.
This is unstable. The fits files are written by patch, which makes them useless, and the python parquet writing is fragile and fails sometimes.
I propose that convert_merged_tract_to_dpdd only deals with HDF5 output (which is robust) and FITS/parquet would come in a later stage that reads the former. This allows to write FITS files per tracts and solve the parquet instability.

**Comment by wmwv** [comment]
I propose that we skip the FITS generate but still generate HDF5 and Parquet.

The Parquet has been useful in several context.  It's worth debugging.

**Comment by wmwv** [comment]
As an implementation `convert_merged_tract_to_dpdd.py` should accept arguments and have the default set accordingly.  This is being done over in #286 as part of the generalization of this script to produce output files from any GCR-available catalog.

**Comment by plaszczy** [comment]
-parquet is important and should be produced. Let see if the new run solves the fastparquet issues (not sure the dpdd hdf5 file looks ok). We may have to dig into this
-FITS files per tract can be obtained easily by post-processsing the dpdd hdf5 files (and concat the pandas df). There still remain the problem of some different schema (float columns for booleans when only Nans) that must be solved if we want to access all the Run data at once (python casts to bool why GCR works but this is not efficient). One solution is to cast all boolean columns to float. Another to chnage the Nan-only colums to False.
