### ISSUE TITLE
Rename data curation/conversion scripts

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-production#302]
The filenames of some of the data curation/conversion scripts sitting under [`/scripts`](https://github.com/LSSTDESC/DC2-production/tree/master/scripts) are not very clear/informative. I suggest we rename them to make their purpose more clear.

Here's one proposal:
- `merge_tract_cat.py` -> `merge_deepCoadd_into_object_cat.py`
- `trim_tract_cat.py` -> `trim_object_cat_columns.py`
- `convert_merged_tract_to_dpdd.py` -> `convert_gcr_object_cat_to_general_formats.py`

**Comment by katrinheitmann** [comment]
@yymao Was your proposal accepted? If yes, can we close this issue, if no, can we resolve this question and then close the issue? Thanks!

**Comment by yymao** [comment]
@wmwv, what do you think? I think the current names are still not very informative. But since there's a README, I am also ok if we just want to keep them as is.

**Comment by wmwv** [comment]
This ticket remains a thing that would be useful.  We should change them someday, but it's never really a priority.

I think this is an example of an Issue that doesn't really need to be closed but is unlikely to get done in the near future.  Unfortunately we lack a better work-tracking system that allows for low-priority tickets to hang around in an easy to manage (i.e., largely ignore) way.

**Comment by yymao** [comment]
This issue is solved in a different way. As we have moved to parquet-based object catalogs, these old scripts are no longer used (but they are not removed from the repo). 

Here's the list of the corresponding new scripts:

- `merge_tract_cat.py` -> deprecated. Use `make_object_catalog.py` instead. 
- `trim_tract_cat.py` -> deprecated. No need to trim object catalogs in parquet format.
- `convert_merged_tract_to_dpdd.py` -> deprecated. Use `write_gcr_to_parquet.py` instead.
