### ISSUE TITLE
halo_id in CosmoDC2

### ISSUE THREAD

**Issue by plaszczy** [LSSTDESC/DC2-production#305]
anomaly (?) observed  on cosmodc2

**Comment by plaszczy** [comment]
when looking at holao_id's on somoDC2_v1.0  I was struck by 2 things
- there are some negative values
-there is about as many unique  id's as  objects3862614101 . here is the (unique) halo stat:

`+-------+------------------+
|summary|             count|
+-------+------------------+
|  count|        3720824405|
|   mean|1.0381070646089787|
| stddev|0.6033381752599895|
|    min|                 1|
|    max|              1339|
+-------+------------------+`
Is this normal/known/corrected (I can hardly verify it on 1.1.4)?

**Comment by yymao** [comment]
Thanks, @plaszczy. Moving this issue to https://github.com/LSSTDESC/cosmodc2/issues/81 and https://github.com/LSSTDESC/cosmodc2/issues/82.
