### ISSUE TITLE
Update Run 1.2i Object catalog with December IN2P3 Run 1.2i reprocessing

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#310]
The first Run 1.2i processing has been redone and new Object Tables should be prepared.

The previous tables will be moved to a "DC2 Run 1.2i alpha" label.

The new tables will replace in the `dc2_object_run1.2i` reader (see https://github.com/LSSTDESC/gcr-catalogs/issues246).

1. [x] Prepare new HDF5 object tables.
2. [x] Prepare trimmed versions.
3. [x] Prepare new DC2 reader: (see `gcr-catalogs` ticket).
4. [x] Generate Parquet file of DPDD quantities.
5. [x] Update README documentation to capture how these were done.

**Comment by JulienPeloton** [comment]
Thanks @wmwv for the list. Do you plan to include `parquet` files as well?

**Comment by wmwv** [comment]
Yes.  Thanks.  That was in my head but not explicitly on the list.  Added.
