### ISSUE TITLE
Create new Object Table 1.2p based on reprocessing

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#315]
* Previous Run 1.2p Tables will be made available as `dc2_object_run1.2p_v3`
* Current will be available as the default `dc2_object_run1.2p` and `dc2_object_run1.2p_v4`
* Run 1.2p reprocessing tracked at
https://github.com/LSSTDESC/ImageProcessingPipelines/issues/80

This re-processing enables cross talk, which was inadvertently disabled in previous run.

* Repo location on NERSC is

/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_39

[x] Prepare new HDF5 object tables.
[x] Prepare trimmed versions.
[x] Prepare new DC2 reader: (see gcr-catalogs ticket https://github.com/LSSTDESC/gcr-catalogs/#256).
[x] Generate Parquet file of DPDD quantities.
[x] Update README documentation to capture how these were done.

**Comment by heather999** [comment]
This new reprocessing also used the updated and fixed calibration, which I don't think we had in dc2_object_run1.2p_v3 (which corresponds to the w_2018_30 reprocessing)
