### ISSUE TITLE
Add --outdir option to DRP DPDD scripts.

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#322]
Add --outdir option to

`merge_tract_cat.py`
`convert_merged_tract_to_dpdd.py`
`merge_parquet_files.py`
`trim_tract_cat.py`

**Comment by wmwv** [comment]
Note that
`write_gcr_to_parquet.py`
already accepts an `--output_filename` argument, which takes care of this need.

**Comment by johannct** [comment]
closing this as it is solved
