### ISSUE TITLE
Define contents of a Visit dataset; provide such a dataset for Run1.2{i,p}

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/DC2-production#331]
Typical use cases of Forced Source data will need access to per-visit information.
To start, implement an example for Run1.2p for which Forced Source data are already available.

**Comment by katrinheitmann** [comment]
@JoanneBogart This issue is open for more than a year. Since we have moved on by now from Run 1.2i/p, I suppose we can close it?

**Comment by JoanneBogart** [comment]
The table run12p_v4.ccdvisit in the PostgreSQL database satisified the requirement.
