### ISSUE TITLE
Long term storage of Run2.0i data

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#334]
We are planning to store the contents of `/global/cscratch1/sd/desc/DC2/Run2.0i` to tape.  This issue is meant to capture the final list of directories and files that are to be stored.  Here are the current contents:
```
desc@cori04:/global/cscratch1/sd/desc/DC2/Run2.0i> ls -l
total 188
drwxrws---+    3 jchiang8 lsst   4096 Oct 24 18:56 NCSA_processing/
drwxrws---+    4 danielsf lsst   4096 Dec 14 07:27 Run2.1i/
drwxrws---+    3 danielsf lsst   4096 Dec 10 10:37 cosmoDC2_v1.1.4/
drwxrws---+   49 desc     lsst   4096 Jan 28 09:57 instCat/
drwxrws---+  448 heitmann lsst  24576 Sep 23  2018 output/
drwxrws---+ 2462 heitmann lsst 135168 Sep 30 12:18 outputs/
drwxrwsr-x+    3 asv13    lsst   4096 Nov 29 07:48 testing_outputs/
```

I propose that `testing_outputs` can be omitted. 
`Run2.1i` may relate to Run2.1i and likely that data exists elsewhere, so it will also be omitted.
I need some guidance on the rest.  Is `output` a subset of `outputs` or are they completely independent and both should be saved?
Does this `NCSA_processing` belong here?

**Comment by villarrealas** [comment]
Everything in `/global/cscratch1/sd/desc/DC2/Run2.0i/Run2.1i`, **NOT to be confused with /DC2/Run2.1i** should already exist on projecta under `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/old_psf_model` and `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/instCat` for outputs and instance catalogs respectively. As such, that particular scratch directory is fine to remove.

**Comment by evevkovacs** [comment]
Just checking, for cosmoDC2_v1.1.4: I assume this is a copy of the extragalactic catalog?

**Comment by villarrealas** [comment]
I've looked around and I will add that `/global/cscratch1/sd/desc/DC2/Run2.0i/outputs` is the one that should be moved to long-term storage. I am not entirely sure what is in `output`, but it seems to be an incomplete version of the former.

I believe this is already on project as `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.0i/sim_data/`.

**Comment by heather999** [comment]
I think I need @danielsf to comment on cosmoDC2_v1.1.4

**Comment by katrinheitmann** [comment]
@heather999 Has this all be figured out now? Or do you still need input? Thanks!

**Comment by heather999** [comment]
The final contents of `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.0i` have changed to include just:  `raw_files` and `instance_catalog`. Both have been copied to HPSS under: `/home/projects/desc/DC2_ImSim/Run2.0i`  Once the contents on HPSS have been verified, the copy on `projecta` will be removed.
