### ISSUE TITLE
Create 'DIAObject' and 'DIASource' tables for sample Run1.2p patch

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#337]
1. Create `DIAObject` table
    - [x] Create scripts
    - [x] Create files
2. Create `DIASource` table 
    - [x] Create scripts
    - [x] Create files
3. [x] Create `gcr-catalogs` `DIASource` reader
4. [x] Create `gcr-catalogs` `DIAObject` reader

Using sample data in

`/global/cscratch1/sd/rearmstr/new_templates/diffim_template`

**Comment by wmwv** [comment]
Seeing mapping at:

https://github.com/lsst/ap_association/blob/master/python/lsst/ap/association/mapApData.py#L109

**Comment by wmwv** [comment]
DIA Source reader created and tested.
Notebook created to do basic verification of DIA source catalog sanity.

**Comment by yymao** [comment]
DIA object catalog was added in https://github.com/LSSTDESC/gcr-catalogs/pull/329
