### ISSUE TITLE
change call to deepCoadd_calexp_calib into deepCoadd_calexp_photoCalib

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/DC2-production#344]
https://github.com/LSSTDESC/DC2-production/blob/881125e14ff0cd5c4ea35b7725273369167cf98a/scripts/merge_tract_cat.py#L197

**Comment by wmwv** [comment]
Ah, yes, right.  Good catch.  I think to preserve backward compatibility we'll have to add a try/except for both `deepCoadd_calexp_calib` and `deepCoadd_calexp_photoCalib`.  Or perhaps a look-up to see what datasets are available from the Butler and choose correctly accordingly.

Thanks for figuring this out.  I was having similar troubles looking at a different repo and hadn't quite realized why.

**Comment by wmwv** [comment]
This was corrected in commit `50f11ee7`
