### ISSUE TITLE
replace  by `from lsst.afw.geom import SpherePoint`?

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/DC2-production#345]
https://github.com/LSSTDESC/DC2-production/blob/881125e14ff0cd5c4ea35b7725273369167cf98a/scripts/merge_source_cat.py#L8

**Comment by katrinheitmann** [comment]
@johannct What is the status of this? Thanks!

**Comment by johannct** [comment]
It is a deprecation warning, assigned to @wmwv . It is still open, but has no urgency.

**Comment by katrinheitmann** [comment]
@wmwv: This is open for more than one year. Any action/comments? Thanks!

**Comment by wmwv** [comment]
This was fixed by #353
