### ISSUE TITLE
Generate 2.1i DR1a DPDD-like data products (e.g., object catalog)

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-production#347]
Now that the 6-month processing of Run2.1i is complete, we need to generate 2.1i DPDD-like data products (e.g., object catalog) for the analysis teams. 

Just when I am writing this, @heather999 informed me that @johannct has already run `merge_tract_cat.py` on IN2P3. If that's indeed the case, then it's just a matter of copying those files to NERSC and creating an entry in `GCRCatalogs`. (In this case, we can probably get this done fairly soon, and the esitimate that I gave @rmandelb would be wrong.)

@heather999 will copy the files to NERSC and I'll take a look. 

The other question is whether we need to create DPDD-like catalogs for source and forced source, @wmwv?

**Comment by johannct** [comment]
yes it has been run, see under `/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/dpdd/calexp-v1\:coadd-v1/object_table_summary`. @airnandez or @heather999 can you deal with the transfer?

**Comment by johannct** [comment]
For the forced sources, it is in the pipeline as well, but has not been run, because I face again the problem that we cannot run cModel photometry here. I will deal with that after I am done with checking metacal results

**Comment by yymao** [comment]
Sounds great. Thanks for the update @johannct!

**Comment by yymao** [comment]
I've made this issue narrower so that it's about DR1a only. For DR1a, we plan to provide only the object catalog (among all DPDD-like products), which is done and released.
