### ISSUE TITLE
Ongoing Run 2.1i Production Tracking

### ISSUE THREAD

**Issue by villarrealas** [LSSTDESC/DC2-production#349]
As we start to work on Run 2.1i on even **more** resources, I'd like to put together a quick issue in order to track what is running where! So listed below is the visit IDs that cover a span of a year + where each Year has been run or will be run.

Current Running of WFD:
Y1: 0 to 262896 / 3056 Visits - old_psf_model [1017 Visits, Cori], y1-y2-wfd [3022 Visits, Cori]
Y2: 262897 to 497968 / 3510 Visits - old_psf_model [1025 Visits, Cori], y1-y2-wfd [3468 Visits, Cori]
Y3: 497969 to 741641 / 3904 Visits - old_psf_model [1401 Visits, Cori], y3-wfd [2785 Visits, Cori]
Y4: 741642 to 991923 / 4064 Visits - in progress (Theta)
Y5: 991924 to 1235517 / 4564 Visits - y5-wfd (Cori)
Y6: 1235518 to 1476729 / 4663 Visits - in progress (UKGrid???)
Y7: 1476730 to 1713246 / 4747 Visits
Y8: 1713247 to 1977249 / 5193 Visits
Y9: 1977250 to 2221326 / 4747 Visits
Y10: 2221327 to 2447932 / 4506 Visits

Current Running of DDF, Unshuffled:
Y5: 991924 to 1235517 - in progress (Cori)

Current Running of DDF, Shuffled:
Plan is to identify a single cadence test to simulate as starting point.

Note that DDF exists in both directories that had obsHistIDs intended to be mixed into this years (but will be processed separately) and a version that has obsHistIDs with a buffer number added onto it. I'll add information about this after working out how we will process these. I'm pinging @jamesp-epcc to confirm regarding the UKGrid, as I believe he should have the information on that.

**Comment by johannct** [comment]
Very useful @villarrealas thanks! If y3 is finished, it should trigger a transfer to CC no?

**Comment by heather999** [comment]
I think we would want the sqlite db updated and fill in the quality_controlled fields for this new data before any transfers occur.  @villarrealas How would the next version of the db be created?  and is it possible to retain the quality controlled field values for y1-y2?

**Comment by johannct** [comment]
ah sorry I thought that was done on the fly.

**Comment by villarrealas** [comment]
I'm still transferring over Y3. I hope to have the db updated by end of tonight (maintaining existing values) and will ping you upon completion. Then you will be free to check to quality control, update those, and then we can begin a transfer!

**Comment by johannct** [comment]
@airnandez y1-y2-wfd calexp are ready. Note that some directories have been overwritten as previous visits suffered from a now cured disease (the iers download timeout). The concerned visits should be

**Comment by heather999** [comment]
@villarrealas As I was working to update the new version of the sqlite3 db: `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim/sqlite_tracking_v1_2.db`, I see that all the quality_controlled values in the `files` table are set to false while in the older version `sqlite_tracking_v1_1.db` I had set them to true for y1-y2-wfd... meanwhile the visits table does seem to have `quality_completed` set to true as I expected.
I'll be updating the files table anyhow, but going forward it would be helpful to maintain both `quality_controlled` and `quality_completed` in both tables as new versions of the db come out.

**Comment by villarrealas** [comment]
I think that's an error on my end. When regenerating the old database with additional fields to carry out a bugfix, I had manually set the quality_completed to true (since you had already checked them). I apparently had missed that I needed to also flip quality_controlled on files to true as well for that.

This was mostly a regeneration because a significant number of bad entries were done due to including unnecessary files. That shouldn't be the case from now on and we should maintain both tables properly.

**Comment by villarrealas** [comment]
Quick update posted regarding the plans for DDF as discussed in the telecon. The unshuffled DDF represents those visits in the normal minion observing strategy and are full focal plane visits. The shuffled DDF represents cadence testing for the Supernovae group and only simulate the four central rafts (and will not be included in coadds). As such, we current aim to simulate the unshuffled DDF to the same depth as WFD, while focusing on a single cadence test for the shuffled as a starting point.

**Comment by wmwv** [comment]
> As such, we current aim to simulate the unshuffled DDF to the same depth as WFD

The same depth (number of images) or the same period of time?
If just the same depth, then may I ask why?  What is the planned use of the images?

My vote would be for the same period of time (and thus many more images and greater depth in the DDF than WFD).

> while focusing on a single cadence test for the shuffled as a starting point.
How many cadence tests are in `instCal_ddf_shuffled`?

**Comment by villarrealas** [comment]
For the first part, by same depth I mean to basically fill in the years: so y5 WFD matched by y5 DDF. I believe that is what you are referring to.

Regarding cadence tests, Scott+Rahul will get back to us after discussion to let us know how things are ordered.

**Comment by wmwv** [comment]
> For the first part, by same depth I mean to basically fill in the years: so y5 WFD matched by y5 DDF. I believe that is what you are referring to.

So same time period => 1.8 mag increase in depth.

In the same time period, the DDF will have a factor of 30x more images/area (in the DDF field) than the WFD and thus a 2.5 log10(sqrt(30)) = 1.8 mag increase in depth.

**Comment by villarrealas** [comment]
I see the confusion. Bad word choice on my end. Goal with the unshuffled will be to keep survey time roughly synced up - e.g. for each year with WFD finished, complete the corresponding DDF visits.

**Comment by katrinheitmann** [comment]
@villarrealas  Since Run 2.1i has come to an end -- should we close this issue?

**Comment by katrinheitmann** [comment]
I am closing this issue now (which is inactive for ~1 year) since Run 2.1i has been retired. Feel free to reopen if you feel it's not done yet. Thanks!
