### ISSUE TITLE
Storage of Run2.1i raw files

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#350]
@airnandez During today's DM-DC2 and CI meetings, it was asked whether IN2P3 plans to store the Run2.1i raw files (i.e. `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim/y1-y2-wfd` ) long term on disk such that DESC collaborators could access them if desired.  At NERSC we are considering moving those raw files from `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim` to HPSS once IN2P3 has completed transferring files from NERSC - primarily due to the need to free up more disk space.  
There is also interest in accessing those raw files at IN2P3 via CVMFS. Is there any possibility that IN2P3 can provide the raw files via CVMFS similar to the DMstack installations which are very useful?

More generally, this is also a question for the Analysis Groups.  Do the groups anticipate needing access to the raw simulated Run2.1i files?

**Comment by airnandez** [comment]
At IN2P3 we do intend to keep on disk the **Run2.1i** raw files, as long as we are collectively working on this run.

I'm not sure I fully understand the meaning of

> ... such that DESC collaborators could access them if desired.

Would DESC collaborators working at NERSC need to *download* those files from IN2P3 or would they need to *regularly read those files' contents using the POSIX API*  (i.e. `open`, `read`, `seek`, `close`, etc.) without pre-downloading them ?

The technical solutions to deploy would be different for those 2 use cases. The CVMFS path is one of the possibilities: I have no experience using CVMFS for that particular use case but I do know that a few experiments (such as LIGO) distribute some data via CVMFS.

My understanding is that this path is not straight forward as CVMFS was not initially designed for that use case, so it is important to me to really understand your use case and make sure that the time invested in deploying a solution is commensurate with the expected impact that solution will have for the community.

As of today, the amount of data at IN2P3 under `.../Run2.1i/sim` is 16 TB (`y1-y2-wfd/`) and at NERSC it is 28TB (`y1-y2-wfd/` and `y3-wfd/`).

**Comment by heather999** [comment]
Just one quick question @airnandez, has `y3-wfd` already been transferred to IN2P3?  Antonio just made that data available yesterday, and I have not yet check that all the FITs files are ok. I will be updating the sqlite database quality_control fields, today, or tomorrow morning.

**Comment by airnandez** [comment]
@heather999 No, at IN2P3 we currently only have `y1-y2-wfd`. I understood that @villarrealas is finishing transferring the data to NERSC and preparing the tracking database and then you have to check for quality of the new set of files.

I will wait for your green light when `y3-wfd` should be transferred to IN2P3.

**Comment by heather999** [comment]
Just to follow up here - the tracking database has been updated and I made a note on the GitHub Issue where we are documenting the transfers: https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86#issuecomment-499735352

**Comment by heather999** [comment]
Sorry for the delay in coming back to this issue @airnandez, what we are requesting is to provide DESC users the ability to easily access the raw simulated data. At NERSC we can store the data to HPSS and provide Globus access.  We do not expect DESC users will require access to the raw files often, but we do anticipate there may be the need to run tests or help diagnose problems periodically. This would be during the processing of Run2.1i data. We should define some timeline, because I expect you will also want to limit how long this data is maintained off tape. Some desired features include:

- Avoid the need for collaborators to obtain an IN2P3 account
- Avoid the need to download files locally

Access to the raw files similar to how we can use the DMstack on CVMFS would be very desirable.  I'm just not sure how feasible that is.  Pinging @cwwalter and @katrinheitmann for their input.

**Comment by katrinheitmann** [comment]
This is an issue concerning Run 2.1i. Since we have retired that dataset, I am closing this issue. @heather999 in particular: If you feel this still needs more work/resolving, feel free to reopen. Thanks!
