### ISSUE TITLE
Just extract FLUXMAG0, don't calculate mag in 'merge_*_cat' routines.

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#352]
Save and extract FLUXMAG0 from DM Science Pipelines output.

Compute magnitudes and nanoJanskys in GCR.

This will also involve wrapping this in a try/except around
new: `getInstFluxAtZeroMagnitude`.
old: `getFluxMag0`.

**Comment by yymao** [comment]
fixed by #358
