### ISSUE TITLE
Add `ipympl` to NERSC Jupyter environments to improve image viewing

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#354]
@heather999 Could you kindly add `ipympl` to the next round of NERSC Jupyter kernel builds?  This will bring us some more advance options and support from `lsst.afw.display` than available through the basic `matplotlib` interface.

I suppose this only needs to added to the `desc-stack` build, but I would suggest adding it to both `desc-stack` and `desc-python` for simplicitly (for both maintainer and user).

**Comment by yymao** [comment]
this should be an issue in https://github.com/LSSTDESC/nersc

**Comment by wmwv** [comment]
Thanks @yymao 
So moved:
https://github.com/LSSTDESC/nersc/issues/13
