### ISSUE TITLE
Request Run2.1i increased SCRATCH quota and turn off purging @NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#356]
We want to retain access to Run2.1i DM processed data on CSCRATCH at NERSC.  It is preferred this data be on SCRATCH at NERSC to allow running batch jobs that utilize the DM Gen2 Butler (there are known locking issues that prevent the use of `projecta` in batch).  Currently we have a quota of 100 TB on `/global/cscratch1/sd/desc/`.  It is nearly full currently but much can be cleared out.  In any case, this is likely not enough to handle both Run1.2i and Run2.1i DM processed data, even if we omit the `calexps`.

As a point of comparison here is a breakdown of the disk space used for `coadd-dr1b-v1` which covers 6 months:
```
du -hs coadd-dr1b-v1
9.1T	coadd-dr1b-v1
du -hs coadd-dr1b-v1-grizy/
8.2T	coadd-dr1b-v1-grizy/
du -hs coadd-dr1b-v1-u     
1.6T	coadd-dr1b-v1-u
```

Before opening a ticket with NERSC, we need to:
* Identify the amount of space required
* Define a timeline to turn off purging

**Comment by katrinheitmann** [comment]
Since Run 2.1i has been retired, I suppose this issue can be closed? @heather999?

**Comment by heather999** [comment]
Yes, this can be closed, in fact there is no longer a need for data to be on CSCRATCH now that we know how to set up select files on CSCRATCH and leave the actual data on CFS.
