### ISSUE TITLE
Run2.1.1i Test Production

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#359]
Continuing investigation into problems in Run2.1i
- 25 sq degrees, 6 months, no-AGNs
- 580 pointings using DR1B: `date < \"2024-01-03T01:19:03.326\" and date > \"2023-07-03T01:19:03.326\"`
https://github.com/LSSTDESC/ImageProcessingPipelines/issues/97#issuecomment-497895037
- Final checkpoint files will be retained and moved to an alternate directory in case AGNs are added later
https://github.com/LSSTDESC/imSim/pull/225
- Initial job estimate 3.4M hours

**Checklist**
Simulation 
- [x] Update imSim handling of checkpoint files https://github.com/LSSTDESC/imSim/pull/225
- [x] Retrieve DR1B instance catalogs from HPSS - Heather
- [x] Update workflow to include [NERSC recommendations](https://docs.nersc.gov/jobs/best-practices/#improve-efficiency-by-preparing-user-environment-before-running )- Antonio
- [x] Small Test Run to demonstrate any lingering performance issues at NERSC - Antonio
- [x] Run validation on simulation output files - Heather
- [x] Copy files to projecta and provide updated sqlite_tracking DB
- [x] Trigger copy to CC - Fabio/Dominique

DM DRP 

- [ ] Test SLAC's https migration which affects the SRS pipeline at IN2P3 (on hold until https transition)
- [x] Test SLAC's https migration at NERSC - Heather (on hold until https transition)
- [x] Confirm we will use the existing Run2.1i reference catalog for now
- [x] Provide an alternate data transfer mechanism (Globus) between IN2P3 and NERSC if Fabio is unavailable for data transfers - Dominique
- [x] Set up new Run2.1.1i DM repo and prepare for running SRS workflow at CC
- [x] Complete processing with skyCorrection at CC - Johann
- [x] Transfer CC processed data to NERSC - Fabio
- [x] Demonstrate running DMDC2_INGEST at NERSC - Heather
- [x] Demonstrate running DMDC2_SINGLEFRAME at NERSC - Heather
- [x] Demonstrate running DMDC2_DRP at NERSC, starting with 4 tracts: 4030, 4029, 3232, 3831 - Heather
- [ ] Reprocess full Run2.1.1i at NERSC with skyCorrection - Heather
- [x] NCSA processing https://jira.lsstcorp.org/browse/DM-21026 - Hsin-Fang

Data Access
- [x] [Update gcr-catalog to include magnitude calculation for `make_object_catalog`](https://github.com/LSSTDESC/gcr-catalogs/issues/369)

Infrastructure and Documentation

**Comment by villarrealas** [comment]
Attached is the full list of pointings selected by Scott for simulation.
[agn_test_pointings_dr1b.txt](https://github.com/LSSTDESC/DC2-production/files/3472842/agn_test_pointings_dr1b.txt)

**Comment by danielsf** [comment]
Here is the list of pointings, filtered to only include those in which 0.25 of the focal plane overlaps the 25 square degree region (note: I added a column reflecting the fraction of the focal plane overlapping the test region)

[agn_test_pointings_dr1b_filtered.txt](https://github.com/LSSTDESC/DC2-production/files/3474187/agn_test_pointings_dr1b_filtered.txt)

**Comment by boutigny** [comment]
Regarding alternate data transfer, I noticed that as there is no public endpoint set up at CC-IN2P3 I am limited to 4 parallel file transfer with my private endpoint and I can't get a throughput better than 800 Mb/s,
I also tried `bbcp` with 10 parallel streams and got > 1.6 Gb/s.
For the record the command is the following:
` bbcp -V -z -s 10 -S "ssh -x -a -oFallBackToRsh=no %I -l %U %H /usr/common/usg/bin/bbcp"  "boutigny@dtn01.nersc.gov:/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr4-v1/object_table_parquet/object_tract_3830.parquet" object_tract_3830.parquet`

**Comment by villarrealas** [comment]
I've started a small test run for 8 nodes to run for 16 hours on Cori. The pipeline has been shifted to mostly operate on cscratch, so this should circumvent a lot of the issues that have been raised with the Cori OS upgrade.

**Comment by heather999** [comment]
Capturing some updates from Slack:
A 2000 node job was started up on Friday, Aug 9th, after the successful small test run and after the emergency Cori update.
As of 8 AM PT this morning we have 45898 fits files. Those have been validated to see that they pass fitsverify and that the centroid files are > 4 MB. Two centroid files were identified as failing the centroid check and will be omitted from processing:  `00458564 (R32 S21) and 00466748 (R43 S21)`
The files will be copied to `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1.1i` and the sqlite_tracking DB will be updated to help coordinate the data transfer to CC.
An initial ingest will be started at NERSC using the same SRS workflow currently in use at CC.

**Comment by villarrealas** [comment]
A transfer database has been generated for those files at `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1.1i/sim/sqlite_tracking_agn-test.db`. I ran into a small issue with files with identical base names + visits with identical obshistID which would require a fairly significant schema change, so a second database was unfortunately more realistic at this time.

**Comment by johannct** [comment]
`/sps/lsst/dataproducts/desc/DC2/Run2.1.1/w_2019_19` setup and `ingest` started. `calexp` will follow shortly.

**Comment by heather999** [comment]
Update on Processing at NERSC
- calexps were produced for all visits
- sky correction was skipped
- coadds are complete for 4 tracts: 4030, 4029, 3832, 3831
- multiband on those same 4 tracts is in progress
- metacal is being skipped for now, due to uncertainty of the versions of the ngmix code to utilize.

More Details here: https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+DRP+DC2+Processing+Run2.1.1i

**Comment by johannct** [comment]
Update on processing at CC : the 14 tracts are done for what concerns the butler files and the parquet object catalogs. This is with SkyCorrection. Metacal is not yet done, and I will need to run the proper parquet file creation, which is in dev.

**Comment by jchiang87** [comment]
Thanks for the update @johannct.   Are there now or will there be object catalog data available that we can transfer to NERSC so people can have a look on Tuesday?

**Comment by heather999** [comment]
As for NERSC, I configured the multibandDriver step and now things are proceeding nicely - for now on those 4 tracts we identified:  4030, 4029, 3832, 3831
This is without skyCorrection or running metacal for now.

I'll see where things stand in the morning and then my intent is to rerun on all the tracts with skyCorrection turned on and see how the processing goes.
The repo is here: `/global/cscratch1/sd/descdm/DC2/Run2.1.1i/w_2019_19/rerun/coadd-v1`  The SRS workflow can be followed here: http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?task=53626677
I'll be writing up more completely how to do this at NERSC and some lessons learned.

**Comment by johannct** [comment]
> Thanks for the update @johannct. Are there now or will there be object catalog data available that we can transfer to NERSC so people can have a look on Tuesday?

@jchiang87 : request submitted to @airnandez https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86#issuecomment-527010014

**Comment by katrinheitmann** [comment]
@heather999 Are we still planning to process the data at NERSC as well? If not, I guess this issue can be closed? I think with regard to processing we have otherwise done everything we wanted to for Run 2.1.1.i? Thanks!

**Comment by heather999** [comment]
At NERSC we have processed Run2.1.1i without sky correction - with some few jobs that need to be restarted and completed.  Processing with sky correction is still TBD at NERSC.
