### ISSUE TITLE
dpdd related scripts need to be adapted for CFHT/Megacam

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/DC2-production#360]
The dpdd related scripts are not compatible with CFHT/Megacam.
I have created the branch u/boutigny/cfht to implement the necessary modifications

**Comment by boutigny** [comment]
I am wondering if we could just keep the filter names as is without changing them to 'u g, r, i, z, y' ? For CFHT, they have u, g, r, i, z, i2, u3, g3, r3, i3, z3 and in some cases we may have visits with 2 different kind of the same band pass. So I think that the simplest thing is to just load the filter names from the registry and keep them as is.
I have implemented this change  in the branch `u/boutigny/cfht`. We may further simplify the code by replacing the filter dictionary with a simple list.

**Comment by boutigny** [comment]
Unfortunately, `trim_tract_cat.py` is also assuming some specific filter names.

**Comment by yymao** [comment]
1. Both `merge_tract_cat.py` and `trim_tract_cat.py` are now deprecated, and we should use `make_object_catalog.py` and `merge_parquet_files.py` to create object catalogs (cf. [instructions](https://github.com/LSSTDESC/DC2-production/pull/358#issuecomment-513359114))

2. In `make_object_catalog.py` ([line 99](https://github.com/LSSTDESC/DC2-production/blob/master/scripts/make_object_catalog.py#L99)), a `filters` argument is available. The `filters` argument only needs to be an iterable of strings, not necessarily single characters. Hence, you can supply `filters='u,g,r,i,z,i2,u3,g3,r3,i3,z3'.split(',')` and it should work. 

3. This `filters` argument mentioned above is however not yet exposed as a command line argument of the script, and this is the part needs fixing. 

4. The new object catalog reader in `gcr-catalogs` also no longer assumes filter names when the object catalogs are generated by `make_object_catalog.py`.

**Comment by boutigny** [comment]
Great ! Thanks a lot. I will try that asap

**Comment by yymao** [comment]
Fixed by #379
