### ISSUE TITLE
DC2 Run 2.2 WFD -- Y1-Y5 or Y6-Y10?

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2-production#373]
All,
We are currently planning for 5 years of DC2 WFD (if it turns out we have more time and energy left after that we might go back for all 10 years). We have to make the final decision about Y1-Y5 or Y6-Y10.

The discussions so far have been that:
- Y1-Y5: we will be able to compare results to the AGN simulations from Run 2.1i directly
- Y6-Y10: It's slightly deeper. Also, at some point we were hoping to clean up Run 2.1i but that has stalled a bit and did not seem in the end too promising.

My decision would be Y1-Y5 but if there are any concerns about this decision, please speak up. We need to start generating instance catalogs VERY soon. Thanks!

**Comment by cwwalter** [comment]
I don't have a strong opinion one way or another, but:

- Are there any analysis cases where having the colors being messed up really wouldn't be a problem and the full 10 years could be used in addition if we did Y6-10?  Or is current 1-5 not useful for all groups?

- Because of a known error in minion one of the other proposals was mostly sampled in the 1st year or so (that is the reason it is shallower). So, the cadence might be more realistic or at least uniform in 6-10.

**Comment by katrinheitmann** [comment]
One worry I have with the Y1-Y5 that we have as part of Run 2.1i is that it has several small flaws that have now been address (the first 6 months or so of Y1 are missing due to our problems in Run 2.0i, the redshifts are incorrect, the AGNs, the SEDs have been now refitted). So if we would want to publish a paper on that data, it has lots of caveats. So I would prefer to not use it for any serious science project.

**Comment by wmwv** [comment]
Year 10 is likely to have a wonky cadence as well as the scheduler works to fill in holes.

**Comment by cwwalter** [comment]
Are we also remaking the 1-5 instance catalogs now for the case we want to either use it now, or if things go well and quickly, come back and do 1-5 afterwards or sometime in the future? Or are we only generating 6-10?

**Comment by katrinheitmann** [comment]
Not understanding the question -- we will be doing Y1-Y5 for DC2, so we are generating Y1-Y5 now for DC2, not Y6-Y10. The decision is to go with Y1-Y5 for DC2.

**Comment by cwwalter** [comment]
Sorry... I typed it backwards for some reason.  I was asking if we are also going to generate 6-10 now (even it goes to tape) while Scott is still here and we know how to do it.

**Comment by katrinheitmann** [comment]
Ah, thanks, that's makes sense. I was wondering about that but haven't quite made up my mind. I am not sure if we first want to see how the instance vs truth tests work out this time.

**Comment by katrinheitmann** [comment]
We will start with Y1-Y5. I will close this issue now.
