### ISSUE TITLE
Creating a release tag of this repo for Run2.2i

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#374]
It would be best to create a release tag for this repository for use during the Run2.2i DM DRP processing. As far as I know, all the required changes are in, though there are some outstanding PRs on this repo.  Pinging @wmwv and @johannct I'm happy to go ahead and make a release tag, just want to make sure there are no pending updates.

**Comment by heather999** [comment]
How do we get closure on this? I'd like to create a release tag for Run2.2i.  Is there anything outstanding that we need?  Unless I hear otherwise, pending some discussion tomorrow - I'll plan to create a tag, and we can always create another on if necessary.  @wmwv @johannct

**Comment by wmwv** [comment]
I know of no impending updates to this area.

**Comment by wmwv** [comment]
It's possible that we'd want to merge

**Comment by jchiang87** [comment]
> It's possible that we'd want to first merge
#378
#379

I think we should just go ahead and merge those PRs.

**Comment by wmwv** [comment]
I've approved #378.  It can be merged and then this release tagged.

#379 would be a civilized thing to have but isn't directly relevant for Run 2.2i processing.

**Comment by heather999** [comment]
Now that #378 has been merged.  I went ahead and created a v0.4.0 tag following previous conventions. We can make follow on tags as needed.  Thanks for the help. Closing this issue
