### ISSUE TITLE
Check that rotSkyPos is correct in the instance catalogs

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2-production#376]
When doing some checks in the summer I found (and @danielsf confirmed) that there were differences in when I calculated rotSkPos by hand and the values that were in the in the run 2 DC2 ICs.  Note that unlike some of the other quantities, this value is not encoded in the minion database. That's because you need to apply the DESC dithering to obtain the value.

I was calculating the value like so:

![image](https://user-images.githubusercontent.com/5562740/68637871-3ea26800-0543-11ea-9481-97fdf6461c8c.png)

There were some things that Scott noticed:

- Some of the instance catalogs (the ones he was looking at) were actually generated on Edison, so it is possible it was something about that system.
- Strangely(!), he found etc could get different results on Cori depending on whether he ran as himself or as the decsim account!  The number he got as himself was the same as we saw as we ran on our laptops.

So, the question is if the rotSkyPos in our current instance catalogs is correct.  There are a few things to consider:
 
- Even if wrong, it may be that we are effectively recalculating this number ourselves in imSim anyway in which case it might not matter.
- We are now making the instance catalogs again on Cori so maybe the problem has disappeared. 

It would be good to confirm that we are using the correct rotation in the simulation.

**Comment by jchiang87** [comment]
I think we're ok.  In the following plot, I've computed the `rotskypos` value from our version of the minion_1016 db using the `descDithered` values exactly as in your code snippet using `lsst_sims w_2019_37` and compared to the values in the Y01 instance catalogs in `/global/cscratch1/sd/descim/instcat_y01_191109`.  Here is a histogram of the fractional differences:
![rotskypos_frac_diff_knl_vs_haswell_y01_instcat](https://user-images.githubusercontent.com/1994473/68702543-def58e00-053d-11ea-8b20-b3a77d7163d2.png)
This is just for ~360 cases, since it's rather slow to extract the `rotskypos` values from the tarballs containing the instance catalogs.  Note that I'm performing the calculations on a Haswell node.

**Comment by cwwalter** [comment]
Thanks!  Sorry for the delay I am at a meeting in Japan now.

I went back an looked at one of my original tests (my calculation vs what was in the IC) and it was 

```
In [2]: (13.106749898703288 - 13.10653188199516528)*3600/1                      
Out[2]: 0.7848601492433716
```

(difference in the 3rd decimal place 0.002 = 0.8 arcseconds)  So that is bigger than what you are seeing, that would be 17 * 1e-6 on your scale.

Did you also try as both decsim or yourself? I went back and looked at my slack discussion with Scott and he said for his tests:

>The difference between running on cori as descim and running on cori as myself was ~ 2*10**-6
The difference between running on cori as myself and whatever is on disk is 10**-4.  

There is one thing I don't quite understand from your test above.  Those values in the IC and when you ran with my snippet were both on Cori right?  What would they be different at all? Could it be related to this decsim difference that Scott reported?

**Comment by jchiang87** [comment]
I only tried under my user id.  The instance catalogs were generated on KNL, I believe, whereas I ran on Haswell.

**Comment by cwwalter** [comment]
> I only tried under my user id. The instance catalogs were generated on KNL, I believe, whereas I ran on Haswell.

OK; I see.. that's bigger than the floating point machine error but there could be other operations in the IC calculation that could blow the difference up I guess.

Do we know the threshold for how big this could be before the differences due to rotation at the edge of the focal plane become comparable to the limit on astrometric error?

**Comment by katrinheitmann** [comment]
@cwwalter @jchiang87 Has this been resolved? If so, can you put a final comment and close the issue? Thanks!

**Comment by katrinheitmann** [comment]
Since there has been no more traffic here for the last 6 months, I am closing this issue now. If we do find an issue with this when doing the DC2 analysis, we should probably start a new issue. If you feel strongly about keeping this open, feel free to reopen. Thanks!
