### ISSUE TITLE
Strong Lens systems: lenspop, lensed SNe

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2-production#40]
@dannygoldstein @tcollett What's the plan for making the strong lens systems for DC2? In Twinkles the sprinkler worked by finding a CatSim galaxy and then turning that into a background source galaxy, replacing it in the instance catalog by 2 or 4 images of itself, arranged around a suitable lens galaxy. If you are given a source galaxy redshift, can lenspop generate plausible values for all the rest of the system's parameters? What about the lensed SNe - any issues with predicting them?

@danielsf Is it possible/straightforward to realize the exact same supernova in 2 or 4 places, with different peak times?

**Comment by katrinheitmann** [comment]
Can one of you capture this discussion in the planning document? 
Probably in Section 5 under CatSim and maybe under remaining tasks? Thanks!

**Comment by drphilmarshall** [comment]
Scott, would you mind takin g care if this please? You should add your name
to then author list too, last time I looked Chris was looking pretty lonely
:-) Thanks!

**Comment by danielsf** [comment]
Sure thing

**Comment by dannygoldstein** [comment]
What are the constraints we must obey in this process? 

Can we only use galaxies generated by CatSim (and move them around), or can we generate galaxies after CatSim is run and place them into images?  E.g., can we  pre-select lens galaxies generated by catsim (ellipticals) and then plant source galaxies behind them drawn from the galaxy redshift distribution truncated at the lens redshift (not generated by catsim, but added in after the fact). 

Once the source and lens galaxies are in place it is easy to generate the glSNe. Host galaxy location is drawn from the host galaxy surface brightness profile, and the SN parameters (mainly absolute magnitude, but we can also put in parameters like x1 and c governing SN Ia diversity if desired) can be drawn from measure distributions that can be optionally conditioned on host galaxy type

**Comment by danielsf** [comment]
You can inject new galaxies into the simulations.  Doing that while taking CatSim galaxies (if you wanted to preserve the number of galaxies in the simulation) is harder, but also possible.  This sounds a lot like the work @jbkalmbach did on the Twinkles `sprinkler`.  I recommend talking to him about how generalizable the `sprinkler` is (i.e. can it be connected to a different population of sources than just the OM10 lens catalog).

**Comment by dannygoldstein** [comment]
Thanks Scott - if we inject new galaxies into the simulation, will that affect our ability to apply weak lensing shear and convergence as described in #2 ? 

Danny

**Comment by danielsf** [comment]
Ah.  Yes, that probably would be more difficult.  As I understand it, we will just have lensing parameters sampled at the sites of galaxies already existing in the catalog.  If you put a galaxy where one did not exist before, we would have to come up with some kind of interpolation scheme, assuming that was a valid thing to do, which I'm not sure it is.  The safest bet if you want to make use of the lensing shear maps coming out of the Cosmological Simulations group is to replace existing galaxies with your lensed systems.

**Comment by dannygoldstein** [comment]
Related to that question, if we injected new galaxies into the images, what information would we have to supply -- just observational parameters like sersic n, R_E, brightness, etc., or physical parameters such as masses?

**Comment by danielsf** [comment]
Observational parameters would be enough.

The parameters expected by PhoSim are documented here

https://bitbucket.org/phosim/phosim_release/wiki/Instance%20Catalog

If you don't have exactly what PhoSim expects, it is pretty easy within CatSim to calculate parameters on-the-fly using parameters that you do have.

**Comment by salmanhabib** [comment]
@danielsf, @dannygoldstein: Regarding shear, we are already using an interpolation scheme to put shears at any given point. So this is not really that much extra work --.

**Comment by danielsf** [comment]
@salmanhabib Is the code and data supporting that interpolation (or, at least, its API) publicly available somewhere so that we can write something in CatSim that calls it?

**Comment by salmanhabib** [comment]
@danielsf Not right now, but we could certainly do that.

**Comment by dannygoldstein** [comment]
@jbkalmbach can you give us a sense of the current status of the sprinkler and what would need to be done to connect it to a non-OM10 catalog?

Danny Goldstein
http://astro.berkeley.edu/~dgold
________________________________

**Comment by drphilmarshall** [comment]
One small comment: by following the Twinkles approach to sprinkling and
matching CatSim galaxies to lenspop  _sources_ (rather than
lenses/deflectors) I think the weak lensing effects provided will be more
meaningful. Still only as accurate as the external shear / convergence
approximation (rather than a full multi-plane ray tracing) but maybe good
enough for some interesting tests? If you inject galaxies at some new
redshift you'd need to interpolate the shear and convergence to that
redshift as well as that position - and if you match the deflectors, you
won't capture the weak lensing effect of mass structure _behind_ the lens.

**Comment by drphilmarshall** [comment]
Hey Bryce, what's your take on adapting the Sprinkler to a non-OM10
catalog? I guess as long as the required columns are there, its just some
plumbing to read the new file, right? Great if you can post a link to the
relevant notebook that shows the Sprinkler in action, for the SL leads to
take a look at. Thanks!

**Comment by jbkalmbach** [comment]
Hi all, sorry about the delay in responding. Yeah, plugging in a new catalog should be no problem. There is an optional parameter in the sprinkler to plug in your own catalog file:

```
class sprinkler():
    def __init__(self, catsim_cat, om10_cat='twinkles_lenses_v2.fits',
                 density_param=1.):
```

As long as it is formatted similar to OM10 it should be fine.

**Comment by cwwalter** [comment]
@jbkalmbach and @drphilmarshall Is this still outstanding?

**Comment by danielsf** [comment]
I think we have done everything we are going to do on this issue for DC2.  I do not believe we have tried running a non-OM10 catalog through the sprinkler.  If that is still of interest, it should probably be its own issue in the Twinkles repo.
