### ISSUE TITLE
Prepare for Run2.2i DR6 v2 release

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#414]
Tract 4852, patch 1,5 has been updated as discussed in #408 
#### Assemble Functional LSST Science Pipeline repository and determine the appropriate name for this release i.e. Run2.2i-dr6-v2
- [x] calibrations, including Brighter-Fatter
- [x] reference catalog
- [x] ingested raws
- [x] calexps
- [x] coadds
- [x] multiband

#### Catalogs

- [x] Copy Object Catalogs into the shared area to a directory named: Run2.2i-dr6-v2pre/object_table_summary
/global/cfs/cdirs/lsst/shared/DC2-prod/*/dpdd
- [x] Copy Metacal, if available, into the shared area in a directory named: Run2.2i-dr6-v2pre/metacal_table_summary
/global/cfs/cdirs/lsst/shared/DC2-prod/*/dpdd
- [x] Produce Truth Match (is there a write up for how this is done?)
- [x] Copy output into shared area: /global/cfs/cdirs/lsst/shared/DC2-prod/*/truth
- [x] Update GCRCatalogs for pre-release including the object catalogs and metacal
- [x] Produce [DPDD Parquet using Object Catalogs](https://github.com/LSSTDESC/DC2-production/blob/master/scripts/README_write_gcr_to_parquet.md)
Store output in the shared area: /global/cfs/cdirs/lsst/shared/DC2-prod/*/dpdd/Run*-dr*-v*pre

#### Add-On Catalogs

- [ ] Inform PZ group and request Photo-Z
When available, copy into shared /global/cfs/cdirs/lsst/shared/DC2-prod/*/addons/photoz
- [ ] Request generation of survey property maps using supreme, note that [Run2.2i-dr6-v1 maps](https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Run2.2i+DR6+Survey+Property+Maps) already exist
When available, copy into shared /global/cfs/cdirs/lsst/shared/DC2-prod/*/addons/supreme

#### Validation

- [ ] Run 2.2i validation notebook
- [ ] Request DC2 team to take a look

#### Final Preparations

- [x] Rename /global/cfs/cdirs/lsst/shared/DC2-prod/*/dpdd/Run*-dr*-v*pre to Run*-dr*-v*, effectively removing the "pre" suffix, i.e. Run2.2i-dr6-v2
- [x] Update or create symlink pointing to the new Run*-dr*-v* directory created in the last step, naming it Run*-dr*, i.e. Run2.2i-dr6 is a symlink pointing to Run2.2i-dr6-v2
- [x] Update or create symlink pointing to the new truth match data under DC2-prod/*/truth/tract_partition/, naming the link match_dr* pointing to match_dr*_v*
- [x] Update and release GCRCatalogs including all available add-on catalogs, object cats, truth match, etc
- [x] Copy LSST Science Pipelines repository to shared area
- [x] Update [Data Products Page](https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Data+Product+Overview)
- [x] Update and tag desc-dc2-dm-data
- [x] Post announcement on Slack

**Comment by heather999** [comment]
@yymao @JoanneBogart Looking through the list, we need truth match to be generated for DR6-v2, this should only impact tract 4852.  We should coordinate updating GCCatalogs to migrate `dc2_object_run2.2i_dr6_v2pre` to `dc2_object_run2.2i_dr6_v2`.  I'll start on a PR.

**Comment by yymao** [comment]
I don't think I've written up a note for the truth-match catalog generation. I can generate it for DR6 v2 and use the chance to write up a note, but I won't be able to get to it until later today. 

Re: object catalog, do we just move the directory `dc2_object_run2.2i_dr6_v2pre` to `dc2_object_run2.2i_dr6_v2`?

**Comment by heather999** [comment]
Yes, I think we should just move `dc2_object_run2.2i_dr6_v2pre` to `dc2_object_run2.2i_dr6_v2`.  I'll go ahead and do that

**Comment by yymao** [comment]
Can you keep a `dc2_object_run2.2i_dr6_v2pre` symlink for now so that we don't break GCRCatalogs? I'll open a PR in `GCRCatalogs` soon

**Comment by yymao** [comment]
Truth-match catalogs are being generated now.

**Comment by heather999** [comment]
Run2.2i DR6-v2 release is complete.
