### ISSUE TITLE
DC2 Data Release [Insert Release ID here]

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/DC2-production#421]
Create markdown template for a data release template.  For now assume it's specifically for DC2.
Most if not all the work is already done: just start with the Confluence page https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Data+Release+Checklist

**Comment by heather999** [comment]
I think I did a lot of this - but it may need updating!  https://github.com/LSSTDESC/DC2-production/issues/templates/edit

**Comment by JoanneBogart** [comment]
Ah, that explains why things seemed to be already filled in!

**Comment by JoanneBogart** [comment]
Moved these updates to the appropriate place.  No need to keep this issue around.
