### ISSUE TITLE
Report flux density in microJansky in DC2 catalogs

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2-production#43]
In #41 we discussed about the addition of a column containing the magnitude for each object (missing in the current dataframes for DC1). @egawiser pointed out that we should be providing the flux density of each object in microJansky since these units were the most appropriate for fainter objects.

**Comment by katrinheitmann** [comment]
@fjaviersanchez Hi Javier, who will take care of this? When you say "catalogs" and "dataframes" I assume you mean this should go into the final DM stack delivered catalog? It would be good to assign this to somebody who can take care of it. Thanks!

**Comment by cwwalter** [comment]
Datataframe in this case is referring to the final data frame we produce for users.  We make these using the DM catalog as an input and the results go either into a hosted qserve database and/or dask data frames. So, if any quantities don't exist in the DM output, we calculate them and add a column.  The same is true for the magnitudes for example.

DM reports fluxes for each algorithm. We may need to manipulate them to get them into the requested form. Just let me know if I didn't make this clear enough.

**Comment by jchiang87** [comment]
This is something we can include in the CICatalogs sprint week project.

**Comment by egawiser** [comment]
@jchiang87 that sounds great.  At the risk of stating the obvious, let me remind that we want uncertainties in microJansky along with flux densities in the same units in the catalogs/database used for analysis.  I was told that Jansky are somehow Project standard units - which is inefficient given that the typical LSST-detected source will have flux density around 0.1 microJy, hence the preference for microJy to avoid everything showing up in scientific notation.

**Comment by katrinheitmann** [comment]
@egawiser @jchiang87 Has this ever been addressed? If not, what would it take to finish this up?

**Comment by jchiang87** [comment]
We would address this when we transcribe the contents of the DRP pipeline catalogs into either a db or pandas data frames.   The exact form of the db or data frames is still TBD to my knowledge.  I reckon we should have a more comprehensive epic to deal with how the DM catalog data is served to the collaboration.

**Comment by katrinheitmann** [comment]
Could you start that epic, please? It will be also good for preparation 
for the next telecon where we will discuss some of these issues. Thanks 
very much!

**Comment by cwwalter** [comment]
I wanted to remind people of this request by @egawiser.  This isn't a standard quantity so we need to calculate it ourself to add to the output data frames etc for truth and reconstructed cases or explain give an example of how to to do this in analysis.

**Comment by wmwv** [comment]
The standard flux unit in the LSST DPDD is now nanoJansky.  The DPDD was updated at the end of October 2018 to specifically to implement this change.

https://docushare.lsstcorp.org/docushare/dsweb/Get/LSE-163/LSE-163_DataProductsDefinitionDocumentDPDD.pdf

as argued in 

https://pstn-001.lsst.io/v/v1.0/fluxunits.pdf

Currently the DM Science Pipelines processing produces fluxes normalized to an AB magnitude of 27.  Future versions, in particular once we start running `jointcal`, will provide fluxes in nanoJansky.

The current `psFlux_*` values in the Object tables as published for Run 1.1p, 1.2p, and 1.2i can easily be converted to nJy by multiplying by 57.54 (= 10^(4.4/2.5) = 10^((22.5+8.90-27)/2.5))).

@yymao and @wmwv will update the Generic Catalog Reader DC2 Object interface next week to implement this change.

**Comment by beckermr** [comment]
I'm flipping out about this change. This kind of effort failed in the SDSS from what I have been told. Amazing!

**Comment by salmanhabib** [comment]
@beckermr flipping out with joy or horror ;-)?

**Comment by beckermr** [comment]
lol. joy! I am like walking around the halls here excitedly and randomly slacking people. this is amazing!

**Comment by RobertLuptonTheGood** [comment]
I laid down the law;  we know the zero points better than the radio folk did, and it turned out that projects interpreted nMaggies in terms of AB fluxes rather than relative to e.g. BD17+4708 -- so why not just go with [n]Jy.  I'm glad someone's happy!

**Comment by wmwv** [comment]
Now that
https://github.com/LSSTDESC/gcr-catalogs/issues/254
has been merged and v0.10.0 put into production at NERSC.

DC2 catalogs now report flux and flux err values in nJy.
