### ISSUE TITLE
Strong Lens systems: AGN and SN host galaxy Einstein rings

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2-production#46]
@tcollett @dannygoldstein @linan7788626 @mpwiesner @jbkalmbach 

Thinking about the strong lens systems to be sprinkled into the ultraDDF part of the DC2 survey. Has the sprinkler been upgraded to include simulated Einstein ring images, to get the SN and AGN hosts right? I know Nan and Matt made a lot of progress on this, but is it ready to be run on the DC2 instance catalogs?

In #40 there is discussion of which input lens catalog to use, lenspop or OM10. Either way, we'd need source galaxy properties to be predicted, and then used to make the input images for PhoSim and/or ImSim.

Suppose we make a 1-10 thousand time delay lenses in the uDDF. Do you want to sprinkle a realistic population of non time-variable lens systems in the main survey area, to support general lens finding? Do these need to include some (or many) compound (double source plane) systems?

All these things are possible - but will take some work. Great if you can indicate what you can help with! Thanks :-)

**Comment by linan7788626** [comment]
> Thinking about the strong lens systems to be sprinkled into the ultraDDF part of the DC2 survey. Has the sprinkler been upgraded to include simulated Einstein ring images, to get the SN and AGN hosts right? I know Nan and Matt made a lot of progress on this, but is it ready to be run on the DC2 instance catalogs? 

Hi @drphilmarshall , currently, we have the modules to create lensed host galaxies if the instance catalogs of the hosts of AGNs are provided. @jbkalmbach gave us a sample input for this, and as it is shown in [Twinkles/issues/455](https://github.com/LSSTDESC/Twinkles/issues/455), the codes for creating lensed hosts of AGNs are ready. @mpwiesner will take over the codes and merge them in. I will collect the codes and send them to Matt asap. Regarding the hosts of SNs, we have not tried yet, but it should be similar to what we did for the hosts of AGNs. Firstly, the input we need is a sample catalog of the hosts of SNs.

> Suppose we make a 1-10 thousand time delay lenses in the uDDF. Do you want to sprinkle a realistic population of non-time-variable lens systems in the main survey area, to support general lens finding? Do these need to include some (or many) compound (double source plane) systems?

It is a good idea that including compound (double source plane) systems. I would like to contribute to this if we decide to involve it. 

Hi @tcollett, if I recall correctly, you have some papers about "double Einstein Crosses" and "double Einstein Rings". What do you think of involving compound systems into LSST? Thanks, :-)

**Comment by dannygoldstein** [comment]
Thanks Nan! To generate SN hosts from a galaxy instance catalog, all that is required is to draw a random SN location from the surface brightness profile of the source galaxy, then add the SN in at that location. I have the following code to do this quickly and analytically for a source galaxy with a Sersic surface brightness profile:

 ```python
    from scipy.special import gammaincinv
    import numpy as np

    def random_location(self):
        """Sample a random (x, y) location from the surface brightness
        profile of the galaxy."""

        bn = gammaincinv(2. * self['n'], 0.5)
        z = np.random.random()
        x = gammaincinv(2. * self['n'], z)
        R = (x / bn)**self['n'] * self['r_eff']
        theta = np.random.random() * 2 * np.pi
        xp, yp = R * np.cos(theta), R * np.sin(theta)
        xt = xp * np.sqrt(1 - self['ellip'])
        yt = yp / np.sqrt(1 - self['ellip'])
        x, y = np.linalg.solve([[np.cos(self['theta']), np.sin(self['theta'])],
                                [-np.sin(self['theta']), np.cos(self['theta'])]],
                               [xt, yt])
        return x + self['x'], y + self['y']
```

As a test, it could be good to just start with a small catalog of spiral galaxies. Is this readily available? If not I can provide one myself. 

@mpwiesner If you point me the code base I can integrate the SN location sampler.

Also @linan7788626 I agree we should push for compound lenses in DC2! There is a paper to be written on that analysis.

**Comment by mpwiesner** [comment]
Hi @dannygoldstein, the most recent code that @linan7788626  produced is here:  https://github.com/linan7788626/hack_with_Matt/tree/master/lensed_hosts_for_Matt.  The main routine is **generating_lensed_hosts.py** to generate fits stamps of lensed hosts.  I then take the output and make instance files for PhoSim.  @drphilmarshall, what is the end product that is needed for DC2, PhoSim fits e-images of each system or something else?

**Comment by dannygoldstein** [comment]
Hi @mpwiesner, @linan7788626, this code looks like it expects a catalog of lensed point sources - where is this catalog calculated?

**Comment by drphilmarshall** [comment]
@mpwiesner I think we need to bolt your script onto The Sprinkler, so that we can make PhoSim instance catalogs that use your little FITS images when generating the DC2 images. And then we'd need to pass this instance catalog and the folder of stamps to the people running PhoSim. Maybe a good project for Sprint Week?

**Comment by linan7788626** [comment]
Hi @dannygoldstein , the catalog of lensed point sources (AGNs only) are from Twinkles II, @jbkalmbach provided it kindly.

Hi @drphilmarshall , a project for Sprint Week sounds great. I will reorganize my codes for @mpwiesner before the Sprint Week.

**Comment by dannygoldstein** [comment]
I have a library of lensed SNe (images + host galaxies + lenses) I can provide, based on an OM10 like sim. but it is not generated by twinkles

i think we should all chat soon @jbkalmbach @rbiswas44 @drphilmarshall  @mpwiesner @linan7788626 to decide how to proceed

perhaps the next scheduled twinkles meeting ?


Danny Goldstein
http://astro.berkeley.edu/~dgold
________________________________

**Comment by mpwiesner** [comment]
@dannygoldstein sounds like a good idea.  @jbkalmbach when is the next scheduled Twinkles meeting?

**Comment by jbkalmbach** [comment]
Hey everybody,

Danny just posted a message about this on slack, but wanted to crosspost here to make sure people saw it. We're proposing a call about DC2 SL time domain inputs on Friday 1200 Pacific time after the general DC2 call. The purpose of this call would be to get organized on what codes we need to make sure we get the desired SL inputs into the DC2 data.

**Comment by cwwalter** [comment]
@jbkalmbach Is this ready to be closed?

**Comment by danielsf** [comment]
I think we can close this issue.  We are generating InstanceCatalogs that include the strong lensing systems.
