### ISSUE TITLE
PhoSim 3.7 Timing Note

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2-production#48]
The PhoSim 3.7 timing tests really should be written up as a DESC Note, so that 1) they are easy to find by anyone in the collaboration and 2) the team gets credit for what was a fair bit of hard work. 

We have John, Glenn and Tom's [test notes](https://docs.google.com/document/d/1f5aoP9ND62NNwdfcex21zYcdnY3VFTZkLgRyYP4yPy8/edit), and also the text Salman wrote for the [NERSC ERCAP request](https://github.com/LSSTDESC/DC2_Repo/files/1507436/Allocation_Estimate_DC2_LSST_DESC.pdf), plus some discussion of the best way to present the  numbers in [#33](https://github.com/LSSTDESC/DC2_Repo/issues/33). This Note should be pretty quick to compile, given suitable plain text or Google doc inputs: here's the [current version, based on the Google doc Note template](https://docs.google.com/document/d/1muXK0tb6Inylrysd4TmXECLLsYclZNQ2_6pYlwFRwy0/edit?usp=sharing). @salmanhabib would you mind pasting in the PhoSim parts of your NERSC text please? And then @TomGlanzman could you and Glenn provide a few more details from your testing results? That should just about do it I think. 

To make this Note easy to find, I declared it on the [Pub Board paper tracking system](https://confluence.slac.stanford.edu/display/LSSTDESC/Interim+LSST+DESC+Paper+Tracking), and listed it as part of the DC2 project (since its main result is the forecast for the DC2 cost).

**Comment by drphilmarshall** [comment]
Authors: here's the live [link](https://docs.google.com/document/d/1muXK0tb6Inylrysd4TmXECLLsYclZNQ2_6pYlwFRwy0/edit?usp=sharing) to the Note file.  @sembrosk, I don't seem to be able to assign this issue to you as well but I'm working on it :-)

**Comment by katrinheitmann** [comment]
@drphilmarshall Hi Phil, PhoSim 3.7 by now has been replaced by much newer PhoSim versions, so I think this issue should be closed. Since you put a link to the notes in the pub board tracking system, we have a record of what was done at least.
