### ISSUE TITLE
Evaluate the truth table code and consider qserve issues

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2-production#57]
We may want to split this issue later (with a separate issue for the db) but, in DC1, the production of the the truth source catalogs that we use for analysis and were put into the dask data frames and sql database were extracted from CatSim.  

The code to do this was written by @jchiang87.  The script lives here:

https://github.com/LSSTDESC/SSim_DC1/blob/ccad38c4ce097bb2d4241361c49dbcf6050f718b/scripts/make_csv_truth.py

and relied on:

https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/imsim_truth.py

It should be noted that this output can be used for both PhoSim and imSim.

We took his output and tried to load a sqlite db at NERSC (which didn't work very well; it was too slow) and also made dask based pandas files so we could work with large files [These were usually used in analysis to make smaller reduced in memory dataframes]

Corresponding / files and tables were made also from the DM output and they were  catalog matched with the star and galaxy truth files so the truth information in these files could be used with the DM output.

See here for some pointers to the matching code (which needs to be updated - this was a possible sprint week project.  A student at SLAC is also working on this):

https://github.com/LSSTDESC/SSim_DC1/issues/51

We should consider if we want to do this the same way in DC2 for the 300 sq degrees and also if products will be loaded into a qserve database.

**Comment by cwwalter** [comment]
Forgot to put in... Our current plan if possible is to try to supply both a qserve relational database and supply dask based data frames.

We can discuss more in detail here.

**Comment by salmanhabib** [comment]
Who is responsible for qserv?

**Comment by cwwalter** [comment]
Hi Salman,

> Who is responsible for qserv?

I'm not positive where responsibility lies.  It is a LSST project and I think several of the main developers (like Fritz I think) are at SLAC now.  @jchiang87 has good contacts with them and can say more.

**Comment by salmanhabib** [comment]
@cwwalter Ok, thanks, I guess @jchiang87 and I have to talk this over --

**Comment by katrinheitmann** [comment]
Truth catalogs and related issue have moved on a lot by now. I think this issue can be closed. @cwwalter feel free to reopen if you feel we are not tracking the truth catalog generation correctly.
