### ISSUE TITLE
modify instance catalogs to contain lensed host galaxy images

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2-production#62]
Subtask of #56.

Given fits images of strongly lensed host galaxies from @linan7788626 and modified instance catalogs containing lensed transient images from @jbkalmbach (see #60), @mpwiesner will produce "final" modified instance catalogs containing lensed transient images AND lensed host galaxies. 

CC @jchiang87 @danielsf

**Comment by danielsf** [comment]
We are producing InstanceCatalogs with strong lenses in them.  I am closing this issue.
