### ISSUE TITLE
Page aligned image sizes

### ISSUE THREAD

**Issue by wadawson** [LSSTDESC/DC2-production#75]
Currently in DC1 the size of the “patches” are 6200 pixels x 6200 pixels. For DC2 can we make the size of these patches page aligned (i.e. n * 4096)? Hopefully this is an easy change to make in the simulation code (image processing step) that will have major performance impacts downstream for operations accessing large number of epochs/patches. For example, if the images were made 4096 x 4096 (or 8192 x 8192) this will efficiently support direct io.

(issue spawned from January 10 #desc-dc2 slack discussion)

**Comment by RobertLuptonTheGood** [comment]
We can do that, but the patches overlap to allow for objects near the edge, so you have to think about that too

**Comment by cwwalter** [comment]
I don't think this discussion ever went anywhere.  The patch size is a function of the DM processing not the simulations itself.  I'm thinking that @heather999 and @nicolaschotard are using the HSC defaults.  Can either of you comment and should we discuss if we need to further follow up on @wadawson's comment?

**Comment by katrinheitmann** [comment]
I am closing this issue now. One year after @cwwalter requested an update, nothing has happened. Since DC2 can't be changed anymore, the patch size is now fixed.
