### ISSUE TITLE
OpSim quantities Required by PhoSim

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/DC2-production#76]
For the enhanced cadence in uDDF, by definition, we will have extra visits that are not in the OpSim database. As it was proposed that for these fields, we will only do phosim simulations rather than galsim simulations, we have to make sure we provide all the columns that phosim obtains from OpSim
through the instance catalog headers produced by catsim. 

@danielsf  Following up on your comments on the DC2 cadence presentation by Phil where you had noted  that columns required by phoSim are described in:

https://bitbucket.org/phosim/phosim_release/wiki/Instance%20Catalog

- Can you remind me how phosim gets its skymodel noise as a function of ra, dec, and time? Does it have its own version of sky brightness that includes contributions from stars, sun, moon etc. 
- If we add an observation, we could get a value of seeing from the seeing table / seeing history (have to check exactly), but is there code required to convert it to `seeing X` 
- rotskypos X : Are there any important constraints to satisfy for this ?
- rightascension X : Is this calculated from ditheredRA in catsim or from fieldRA ? If fieldRA, how is the dither information passed to phosim?

**Comment by johnrpeterson** [comment]
1)  yes.  phosim predicts various emission components that result in background.
2)  you can either have phosim predict the seeing (setting it to -1 causes it to choose it from a distribution) or you specify it as the "seeing X".  you wouldn't need code to convert it though.
3) rotskypos could really be anything 
4)   so the dither commands in phosim are purely for bookkeeping purposes.  so you should already convert your RA/dec and feed that to phosim via the pointingra/pointingdec commands.  then the dither is just so you can put the information in the fits header if you want to keep track how you were doing the dither.

hope this is clear.   feel free to ask more.

john

**Comment by danielsf** [comment]
And now the CatSim perspective:

for reference, the method that writes the headers for PhoSim InstanceCatalogs is here

https://github.com/lsst/sims_catUtils/blob/master/python/lsst/sims/catUtils/exampleCatalogDefinitions/phoSimCatalogExamples.py#L96

to answer your specific questions

1) what John said

2) we don't have methods in CatSim to calculate seeing from first principles.  I assume that the concern is we want realistic time evolution in seeing between what occurs in the uDDF visists and what happens in the WFD visits, which will be drawn from OpSim.  It should be possible to produce the `rawSeeing` value that OpSim would have produced if it had observed a given position at a given time.  I assume that code lives in `sims_operations`.  That might be a question for @yoachim or @rhiannonlynne .

3) the relationship between `rotSkyPos` and `rotTelPos` can be enforced using this method

https://github.com/lsst/sims_utils/blob/master/python/lsst/sims/utils/CompoundCoordinateTransformations.py#L252 

there is also `getRotSkyPos` for going from `rotTelPos` to `rotSkyPos`

4) In DC1, we used the `ditheredRA/Dec` columns from Humna's modified version of minion_1016.  If you just set `obs_metadata.pointingRA` and `obs_metadata.pointingDec` to those values before passing `obs_metadata` into the InstanceCatalog, the PhoSim header-writing method will do the right thing.

**Comment by johnrpeterson** [comment]
by the way if you use the seeing -1 to choose from a distribution, it will not only choose realistic values but also have the proper time correlations.

**Comment by yoachim** [comment]
Yes, the seeing and cloud distributions used by OpSim are here:
https://github.com/lsst-sims/sims_ocs/tree/master/python/lsst/sims/ocs/environment

We've requested a few times that this and things like the scheduled downtime be broken out into their own repo to make it easier for other folks to access and use.

**Comment by rbiswas4** [comment]
Thank you! Will reopen if I have more questions:

@johnrpeterson : thanks! I think we would like to have the ability to set seeing for both phosim and imsim to the same value. Right @cwwalter ?
@yoachim : Thanks ... and :+1 on the request too.

**Comment by cwwalter** [comment]
> I think we would like to have the ability to set seeing for both phosim and imsim to the same value. Right @cwwalter

Right.  You can use the same seeing command card in the imSim instance catalog.  If they are being produced by the OpSim database you will have the same values for both simulations on a visit to visit basis.

One thing I can't remember: @johnrpeterson maybe you can you explain for us:  Given an input seeing value via the card, how do you convert that to a physical parameter which is used in the atmospheric model in the ray tracing?

**Comment by johnrpeterson** [comment]
yes, chris, it will generate that consistent seeing, if you provide that parameter.

**Comment by cwwalter** [comment]
> yes, chris, it will generate that consistent seeing, if you provide that parameter.

Right, I know it will be consistent from visit to visit with the same input, but I would like to know how you go from that input parameter to a physical parameter of your model.  Did you tune or calibrate one of the parameters in the Von Karman model to get that effective seeing to come out?

**Comment by johnrpeterson** [comment]
no this is quite complicated and was a couple years of work.

**Comment by cwwalter** [comment]
Your colleagues are capable of understanding your work.  

In the PhoSim paper it says "We can use this model in two different ways. First, if a random atmosphere is desired, we simply draw turbulence intensities from this model. Second, to obtain a particular seeing, we run this model hundreds of time to produce the desired seeing. In either case, the final turbulence intensity values are used to normalize each screen."

We are asking for more detail of what actually happens in usage before we use your model.  Modulo the outer scale it should be closely related to the Fried parameter in each layer.

**Comment by johnrpeterson** [comment]
Chris i am not saying you can't understand it.  I am just saying that this is too complicated to get into in a GitHub issue thread.

**Comment by salmanhabib** [comment]
I agree with John -- these things are more serious than issues, we need to come up with a better way.

**Comment by cwwalter** [comment]
I am perfectly happy to be pointed to a paper or technical report. Or to have you write it up separately and have you point us there.  Things that are complicated need not be explained here. But an answer which explains that and points us to information or says we should discuss it more somewhere else along with barebones explanation is appreciated.

**Comment by salmanhabib** [comment]
@cwwalter  Ok, so when John has a paper or technical report, he can make it available (and I am sure he will), that would be reasonable. Meantime, my main worry is that the result be more or less right. That's what is way more concerning. If there are tests, please suggest them. If ImSim and PhoSim have small differences, c'est la vie. Anyway, this is not the real sky.

Just as for the speckle problem, we don't need to understand the full details of PhoSim right now, the basic point being that the results ought to look reasonable enough for the science WGs to do their job. 

As another example, if you were to ask us for details of the simulation code that is generating the galaxy catalog and we did not have it written up to anyone's detailed satisfaction (BTW, we don't), it could be, in principle, way more problematic.

**Comment by cwwalter** [comment]
@rbiswas4 I'm not sure there is an outstanding issue it is possible for us to address left in this issue.  Can you tell us if there is something specific you would like us to follow up on or if we can close this?

**Comment by katrinheitmann** [comment]
@rbiswas4 I am closing this now -- if we need to address anything in here still, please feel free to reopen. Thanks!
