### ISSUE TITLE
Make the galaxy truth tables have a single entry per galaxy and add all wanted truth info.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2-production#78]
Currently, we write the truth tables as we write the instance catalogs: one entry each for the disk and bulge components that exist.    For DC1 I wrote code afterwards that tried to combine them and also calculated the combined magnitude.  But really, the format should be extended so that in addition to this we store the individual sersic components and magnitudes etc.

Also, with @EiffL's work we can add any random walk info that was passed into the imSim instance catalog.  I know in the last few days @danielsf made a comment in *some* issue that CatSim was already setup to write the truth tables in a different combined format but I couldn't find it.  

This is a reminder to make sure we do it and we spent a bit of time thinking through what information should be in the entries.   Since the catalog has now been read in by the GCR I assume this means we could also add the HOD etc.  This means we should check we are also loading everything we might want to write out.  We of course may also want to just be set up to join to another table with the ID and we also need to consider how the sprinkler affects this as this was not something we had to deal with in DC1.

**Comment by jchiang87** [comment]
Scott mentioned this in a comment in the DC2 checklist google doc. Here is the relevant module: 
https://github.com/lsst/sims_catalogs/blob/master/python/lsst/sims/catalogs/definitions/ParallelCatalogWriter.py

**Comment by katrinheitmann** [comment]
@cwwalter Is this issue the same as #86? If so, can we close this one? Thanks!

**Comment by cwwalter** [comment]
@katrinheitmann I think they are different.  This one is explicitly about making one entry per galaxy.  The other mentions this but is really about choosing format(s) for the truth tables. Pandas, SQL DB etc etc.

It's possible #86 should be subsumed into a more general issue for catalog format since as I mentioned in the issue:

 "One important thing to remember is that the truth tables should be of the same format as the DM output catalog for things like catalog matching and being able to make comparison plots etc."

Maybe combine #86 with #117 that was made by @jchiang87?

**Comment by katrinheitmann** [comment]
I leave it up to you three how to combined them -- it's just difficult 
(at least for me) to track too many issues. So I was trying to do some 
house-cleaning today. Thanks!

**Comment by cwwalter** [comment]
OK I combined the other two and left this one alone.

**Comment by fjaviersanchez** [comment]
@cwwalter question related to this (that we already discussed in some telecon in the past but I can't find any related issue): whose responsibility would be to match inputs (PhoSim/truth catalog) and outputs (DM catalog)? 

In principle, I would say that most analyses will be fine with a simple spatial matching at the catalog level and that this is probably something that we could provide and/or that the analysis working groups can easily obtain but, are there other analyses where people are interested in propagating pixel level "truth" information (such as the PhoSim centroid files) into the final catalogs? @SimonKrughoff do you know if there is already a way to match the DM detected footprints to the PhoSim outputs? Can we propagate the input IDs somehow into the outputs beyond a "simple" centroid matching? Do we even want this for DC2 or should this be part of DC3? I would say that projects like the DM-stack emulation will depend a lot on the selected matching strategies. Also pinging @katrinheitmann and @rmandelb.

**Comment by SimonKrughoff** [comment]
>  @SimonKrughoff do you know if there is already a way to match the DM detected footprints to the PhoSim outputs?

I'm afraid I don't completely understand the question here.  Are the PhoSim outputs the centroid files?  If so, the best we can do is to do a spatial match in pixel space (possibly with a flux prior).    Were you wanting something more?

We have talked about simulating each object in an individual image plane, but that seems expensive, in terms of space.  That would allow direct comparison with deblending algorithms.  We could do that for a subset of images, but I'm not sure it's worth doing for the whole DC2 survey.

**Comment by katrinheitmann** [comment]
@cwwalter @fjaviersanchez Hi there -- this issue has not seen any action for more than a year. Can we close it? Thanks!

**Comment by cwwalter** [comment]
I don't think we can close this quite yet.  There was a recent issue (where? In this repo?) where this came up again.  @danielsf pointed out that we can now make the truth catalogs from the cosmoDC2 catalog (as opposed to the instance catalogs or centroid flees like before) but I don't think that issue came to a conclusion as to how to do it.

I suggest this if we close this issue we merge it with that one.  The main issue is to make a truth catalog where there is only one entry per galaxy and it tells you the fraction of flux that went into bugle, disk, knots etc.  It should also  be attached to HOD...

@danielsf do we have a confirmed/approved plan to do that yet?

**Comment by danielsf** [comment]
I was technically proposing that we use cosmoDC2 *as* the truth catalog (not that we produce anything extra from cosmoDC2).  Yao counter-proposed that we write a new truth reader for cosmoDC2.

That issue is here

https://github.com/LSSTDESC/DC2-production/issues/346

**Comment by yymao** [comment]
We don't need a new truth catalog reader if people don't mind that stars and galaxies appear in two different catalogs.

**Comment by cwwalter** [comment]
Hmm.. I suspect separating stars and galaxies wouldn't be a problem.

But what actually "is" cosmoDC2?  I mean I thought it was a pretty heavy large complicated dataset.  For the DPDD products I can open the parquet files with pandas.  Is the only option here to use the GCR reader to get what you need from that large data set at NERSC?  Perhaps there is still some utility in producing DPDD like reduced truth tables?

**Comment by yymao** [comment]
cosmoDC2 is a set of hdf5 files with certain storage format (but not pandas hdf5). The reader is meant to make it easy to access these files. The reader just retrieve the data for you, and you can easily convert it to pandas DataFrame is that's what you want to use. 

I am not if we will want to duplicate a subset of cosmoDC2 and store them in a different format. I understand that it can be useful, but it also seems that we are tight on storage space.

**Comment by danielsf** [comment]
I suspect that the number of rows involved in the full Run 2.1i truth catalog would prevent us from making something that can just be read into memory with pandas, anyway.  There are 9.4*10**8 galaxies that pass the r<=29 cut we applied for Run 2.1i.  All of those would need truth catalog entries.

**Comment by cwwalter** [comment]
Hmm.. OK let me ask this a different way: how much information  is in the cosmoDC2 data structure that we wouldn't need in a truth table like we had before.

Speed of access and relocatability are also important.  But if we are just copying 100% of the information into a new file and it takes up the same amount of space, I agree that it doesn't make sense to make something new.

**Comment by danielsf** [comment]
There are many tens of columns in cosmoDC2 that one would not need for the truth table, but the GCR is pretty fast when you only ask it for a subset of columns, so there shouldn't be a lot of overhead in just using cosmoDC2 as your truth table.  I believe Yao built GCR with column-based storage in mind.

**Comment by cwwalter** [comment]
Is this already working with a standard suggested query?  Or does it still need to be built?

**Comment by danielsf** [comment]
I don't know that anyone has written down the suggested query, but it will be 1-3 lines of code, so shouldn't be a burden on anyone.

**Comment by yymao** [comment]
While GCR is indeed built with column-based access in mind, the actual loading speed still depends on whether the underlying format supports column-based access. Fortunately the current format used by cosmoDC2 does. 

Not quite sure what @cwwalter means by "a standard suggested query". Here's an example of loading the RA, Dec, and r-band mag of all galaxies with r < 21 into pandas DataFrame. 

```python
import GCRCatalogs
import pandas as pd

cat = GCRCatalogs.load_catalog('cosmoDC2')
data = cat.get_quantities(['ra', 'dec', 'mag_r_lsst'], filters=['mag_r_lsst < 21'])
data = pd.DataFrame(data)
```

Obviously one cannot convert arbitrary large datasets into pandas DataFrame. GCR also support iterating over chunks of the datasets for users to work with large datasets that are stored in chunks (like cosmoDC2).

**Comment by cwwalter** [comment]
> While GCR is indeed built with column-based access in mind, the actual loading speed still depends on whether the underlying format supports column-based access. Fortunately the current format used by cosmoDC2 does.
> 

OK great.

> Not quite sure what @cwwalter means by "a standard suggested query". Here's an example of loading the RA, Dec, and r-band mag of all galaxies with r < 21 into pandas DataFrame.

I meant a list of the typical things you would need for matching, truth etc. and wanted to confirm that is was all working in that in addition to the ra, dec etc you could also grab things like the halo mass etc. if you wanted.  So, as far as you are concerned, all needed functionality exists? That is what I am really asking.

> Obviously one cannot convert arbitrary large datasets into pandas DataFrame. GCR also support iterating over chunks of the datasets for users to work with large datasets that are stored in chunks (like cosmoDC2).

Sure, I meant with something like dask, and extracting reduced sets for things like using it faster and elsewhere (e.g. LSP) .  If a lot of people do that we could wind up with more disk space used than if we just make a file, but there is no reason to address that unless it actually happens.

OK this sounds good.  There is also #346.  Is there something we should do to document this or implement anything else before these can be closed?

**Comment by yymao** [comment]
> I meant a list of the typical things you would need for matching, truth etc. and wanted to confirm that is was all working in that in addition to the ra, dec etc you could also grab things like the halo mass etc. if you wanted. So, as far as you are concerned, all needed functionality exists? That is what I am really asking.

Yes, all the functionality mentioned exist in GCR and works for cosmoDC2. In fact, we made a tutorial notebook that demonstrate matching protoDC2 and object catalog 1.x, using GCR. We should update that notebook to use cosmoDC2 and object catalog 2.1. 

> Sure, I meant with something like dask, and extracting reduced sets for things like using it faster and elsewhere (e.g. LSP) . If a lot of people do that we could wind up with more disk space used than if we just make a file, but there is no reason to address that unless it actually happens.

Yes. And this is one of the reasons that we want future catalogs all use parquet format (#333). For now, since cosmoDC2 is already written on disk, it doesn't quite make sense to just rewrite, unless there is a clear need (like the scenario you mentioned). 

> There is also #346. Is there something we should do to document this or implement anything else before these can be closed?

If there is no clear need of a separated truth catalog, then we can just close both this and #346. Maybe we should just open an issue in https://github.com/LSSTDESC/DC2-analysis for adding a new tutorial of matching cosmoDC2 and object catalog 2.1.

**Comment by cwwalter** [comment]
> If there is no clear need of a separated truth catalog, then we can just close both this and #346. Maybe we should just open an issue in https://github.com/LSSTDESC/DC2-analysis for adding a new tutorial of matching cosmoDC2 and object catalog 2.1.

I think that sounds reasonable.  Could you make that and then close these two with a reference in each to it?

**Comment by yymao** [comment]
Will do. BTW do we have the star truth catalog ready (will be needed in the matching tutorial notebook, I assume), @danielsf?

**Comment by cwwalter** [comment]
> BTW do we have the star truth catalog ready

Do we need a separate issue for this if no?

**Comment by danielsf** [comment]
No.  We do not yet have a truth catalog for the stars.

**Comment by cwwalter** [comment]
BTW, Also, going back to my original questions in the top of this issue. We also have access to the individual components (e.g. sersic indices, magnitudes, and knot parameters) separately available via the GCR correct?

**Comment by yymao** [comment]
> No. We do not yet have a truth catalog for the stars.

OK, then I guess we should leave #346 open for the star truth catalog. 

> BTW, Also, going back to my original questions in the top of this issue. We also have access to the individual components (e.g. sersic indices, magnitudes, and knot parameters) for each galaxy separately available via the GCR correct?

Yes

**Comment by cwwalter** [comment]
OK, I agree.

**Comment by yymao** [comment]
Thank you both. Closing this now. 

- Further questions/comments about the truth catalog of non-galaxy objects should go to #346. 
- Further questions/comments about usage/example of matching cosmoDC2 to object catalog should go to https://github.com/LSSTDESC/DC2-analysis/issues/90
